-- ============================================================
-- ATLETIX · Biblioteca de ACCESORIOS DE CALISTENIA · LOTE 1 (51 ejercicios)
-- Empuje / Tirón / Hombros / Bíceps / Tríceps
-- Requiere 0022. Idempotente: on conflict (nombre, disciplina) do nothing.
-- ============================================================

-- LOTE 1 · Empuje / Tirón / Hombros / Bíceps / Tríceps

insert into public.exercises
  (nombre, nombre_en, aliases, disciplina, categoria, subcategoria, tipo, dificultad, nivel_dificultad,
   equipamiento, tipo_resistencia, tipo_ejercicio, patron, musculos_primarios, musculos_secundarios,
   musculos_estabilizadores, unilateral, cadena_cinetica, objetivo, series_sugeridas, reps_sugeridas,
   descanso_seg, rir_sugerido, descripcion, instrucciones, errores_comunes, precauciones,
   criterio_progresion, regresion, variantes, sustitutos)
values
('Press banca con barra', 'Barbell bench press', 'press de banca plano, bench press', 'Accesorios Calistenia', 'Empuje', 'Empuje horizontal', 'Accesorios Calistenia', 'Intermedio', 2, 'Banco plano, barra y discos', 'Barra', 'Compuesto', 'Empuje horizontal', array['Pectoral mayor'], array['Deltoides anterior', 'Tríceps braquial'], array['Romboides', 'Manguito rotador', 'Serrato anterior'], false, 'Abierta', 'Fuerza', 4, '6-10', 150, 2, 'Empuje horizontal base para ganar fuerza y masa de pecho, hombro anterior y tríceps; sostiene el empuje de skills como planche y 90°.', 'Acostado con pies firmes, omóplatos retraídos y deprimidos; agarre algo más ancho que hombros. Bajá controlado al esternón y empujá extendiendo sin perder la retracción.', 'Rebotar en el pecho; abrir codos a 90°; perder retracción escapular; despegar la cadera.', 'Usá seguridad o asistencia; no bajes al cuello; controlá la barra en todo el recorrido.', 'Cuando hacés 4x8 con RIR 2 sin perder técnica, subí 2,5-5 kg.', 'Press con mancuernas, flexiones lastradas o press en el suelo.', array['Press con pausa de 2 s', 'Press agarre cerrado', 'Press inclinado'], array['Press con mancuernas', 'Flexiones lastradas', 'Fondos en paralelas']),

('Press banca inclinado con barra', 'Incline barbell bench press', 'press inclinado con barra', 'Accesorios Calistenia', 'Empuje', 'Empuje horizontal', 'Accesorios Calistenia', 'Intermedio', 2, 'Banco inclinado, barra y discos', 'Barra', 'Compuesto', 'Empuje horizontal', array['Pectoral mayor (clavicular)'], array['Deltoides anterior', 'Tríceps braquial'], array['Romboides', 'Serrato anterior'], false, 'Abierta', 'Hipertrofia', 4, '8-12', 120, 2, 'Empuje inclinado que enfatiza el pecho superior y el hombro anterior, clave para la protracción fuerte en anillas.', 'Banco a 30-45°, pies firmes y omóplatos retraídos. Bajá a la parte alta del pecho y empujá en línea ligeramente hacia atrás.', 'Inclinación excesiva (>45°) que lo vuelve press de hombros; bajar al esternón; perder retracción.', 'Evitá inclinaciones altas si molesta el hombro anterior.', 'Subí carga al completar 4x10 con RIR 2 sin perder el ángulo.', 'Press inclinado con mancuernas o en el suelo inclinado.', array['Press inclinado con mancuernas', 'Press inclinado con pausa'], array['Press inclinado con mancuernas', 'Press militar con barra']),

('Press banca con mancuernas', 'Dumbbell bench press', 'press plano con mancuernas', 'Accesorios Calistenia', 'Empuje', 'Empuje horizontal', 'Accesorios Calistenia', 'Principiante', 1, 'Banco plano y mancuernas', 'Mancuernas', 'Compuesto', 'Empuje horizontal', array['Pectoral mayor'], array['Deltoides anterior', 'Tríceps braquial'], array['Romboides', 'Manguito rotador'], false, 'Abierta', 'Hipertrofia', 4, '8-12', 120, 2, 'Versión con mancuernas que da más rango y corrige asimetrías de fuerza entre lados.', 'Una mancuerna por mano, omóplatos retraídos. Bajá hasta estirar el pecho y empujá juntando apenas las manos.', 'Bajar demasiado y forzar el hombro; abrir codos en cruz; perder retracción.', 'Controlá las mancuernas al soltarlas; no uses cargas que no puedas estabilizar.', 'Aumentá 1-2 kg por mancuerna al completar 4x10 con RIR 2.', 'Flexiones lastradas o press con mancuernas en el suelo.', array['Press neutro (martillo)', 'Press a una mano'], array['Press banca con barra', 'Flexiones lastradas']),

('Press inclinado con mancuernas', 'Incline dumbbell press', 'press inclinado mancuernas', 'Accesorios Calistenia', 'Empuje', 'Empuje horizontal', 'Accesorios Calistenia', 'Principiante', 1, 'Banco inclinado y mancuernas', 'Mancuernas', 'Compuesto', 'Empuje horizontal', array['Pectoral mayor (clavicular)'], array['Deltoides anterior', 'Tríceps braquial'], array['Serrato anterior'], false, 'Abierta', 'Hipertrofia', 4, '8-12', 120, 2, 'Press inclinado con mancuernas, gran opción para pecho superior y control del hombro.', 'Banco a 30°. Bajá a la línea del pecho alto y empujá arriba y ligeramente adentro sin choques.', 'Inclinación excesiva; bajar demasiado; perder control por fatiga.', 'Elevá las mancuernas con ayuda si la carga es alta.', 'Subí carga o reps al llegar a 4x10 RIR 2.', 'Press inclinado con barra a menor ángulo.', array['Press Arnold', 'Press inclinado neutro'], array['Press inclinado con barra', 'Press militar con mancuernas']),

('Press militar de pie con barra', 'Standing overhead press', 'press de hombros de pie, OHP', 'Accesorios Calistenia', 'Empuje', 'Empuje vertical', 'Accesorios Calistenia', 'Intermedio', 3, 'Barra y discos', 'Barra', 'Compuesto', 'Empuje vertical', array['Deltoides anterior'], array['Tríceps braquial', 'Pectoral superior'], array['Core', 'Glúteos', 'Serrato anterior'], false, 'Abierta', 'Fuerza', 4, '5-8', 150, 2, 'Empuje vertical de pie que construye hombros fuertes y un core que transfiere a handstand y press a pino.', 'Barra a la altura de clavículas, core firme y glúteos activos. Empujá la barra sobre la cabeza llevando la cabeza adelante al pasar.', 'Arquear la espalda baja; empujar hacia adelante; no bloquear el core.', 'Si hay molestia lumbar, hacelo sentado con respaldo.', 'Subí 2,5 kg al lograr 4x6 con RIR 2 y sin hiperextensión.', 'Press militar sentado con mancuernas o press con mancuernas.', array['Press con pausa', 'Press sentado con barra'], array['Press militar con mancuernas', 'Pike push up lastrado']),

('Press militar sentado con mancuernas', 'Seated dumbbell shoulder press', 'press sentado con mancuernas', 'Accesorios Calistenia', 'Empuje', 'Empuje vertical', 'Accesorios Calistenia', 'Principiante', 1, 'Banco con respaldo y mancuernas', 'Mancuernas', 'Compuesto', 'Empuje vertical', array['Deltoides anterior'], array['Tríceps braquial'], array['Serrato anterior', 'Romboides'], false, 'Abierta', 'Hipertrofia', 4, '8-12', 120, 2, 'Press vertical sentado que aísla mejor los hombros y permite progresar sin exigir tanto al core.', 'Espalda apoyada, mancuernas a la altura de orejas. Empujá hacia arriba juntando ligeramente sin choque.', 'Arquear la zona lumbar; bajar demasiado; perder control en el descenso.', 'Mantené el respaldo firme; evitá cargas que desestabilicen el hombro.', 'Subí 1-2 kg por mancuerna al completar 4x10 RIR 2.', 'Press con mancuernas neutro o pike push up.', array['Press Arnold', 'Press neutro'], array['Press militar con barra', 'Press Arnold']),

('Press landmine a una mano', 'Single-arm landmine press', 'press landmine', 'Accesorios Calistenia', 'Empuje', 'Empuje vertical', 'Accesorios Calistenia', 'Principiante', 2, 'Barra en esquina, discos', 'Barra', 'Compuesto', 'Empuje vertical', array['Deltoides anterior'], array['Pectoral superior', 'Tríceps braquial'], array['Core', 'Serrato anterior'], true, 'Cerrada', 'Fuerza', 3, '8-10', 90, 2, 'Empuje unilateral en ángulo, muy amigable con el hombro y útil para estabilidad del manguito.', 'De pie o arrodillado, sujetá el extremo de la barra a la altura del hombro y empujá hacia arriba y adelante.', 'Rotar el tronco; encoger el hombro; usar impulso de piernas.', 'Asegurá bien la barra en la esquina para que no se mueva.', 'Agregá repeticiones y luego carga hasta 3x10 con RIR 2.', 'Press con mancuerna a una mano.', array['Landmine a dos manos', 'Landmine de rodillas'], array['Press militar con mancuernas', 'Pike push up']),

('Fondos en paralelas lastrados', 'Weighted parallel bar dips', 'fondos lastrados', 'Accesorios Calistenia', 'Empuje', 'Fondos', 'Accesorios Calistenia', 'Intermedio', 3, 'Paralelas y lastre (cinturón o mancuerna)', 'Peso corporal', 'Compuesto', 'Empuje vertical', array['Pectoral mayor', 'Tríceps braquial'], array['Deltoides anterior'], array['Romboides', 'Serrato anterior', 'Core'], false, 'Cerrada', 'Fuerza', 4, '5-8', 150, 2, 'Empuje cerrado con lastre, el accesorio de fuerza más directo para dips, planche y muscle up.', 'En paralelas, hombros deprimidos. Bajá hasta 90° de codo inclinando el torso y empujá hasta extender.', 'Bajar demasiado sin control; hombros elevados; codos muy abiertos.', 'Progresá el lastre de a poco; evitá si hay dolor de hombro anterior.', 'Añadí lastre cuando lográs 4x8 estrictas sin balanceo.', 'Fondos a peso corporal o fondos en banco.', array['Fondos con pausa', 'Fondos en anillas'], array['Fondos en anillas lastrados', 'Press banca con barra']),

('Fondos en anillas lastrados', 'Weighted ring dips', 'fondos en anillas con lastre', 'Accesorios Calistenia', 'Empuje', 'Fondos', 'Accesorios Calistenia', 'Avanzado', 4, 'Anillas y lastre', 'Peso corporal', 'Compuesto', 'Empuje vertical', array['Pectoral mayor', 'Tríceps braquial'], array['Deltoides anterior'], array['Manguito rotador', 'Serrato anterior', 'Core'], false, 'Cerrada', 'Fuerza', 4, '4-8', 150, 2, 'Versión en anillas que suma exigencia de estabilización y transferencia directa a skills en anillas.', 'Anillas a la altura de caderas, asegurá el apoyo y bajá controlado hasta 90° manteniendo el anillo pegado al cuerpo.', 'Dejar que las anillas se abran; bajar sin control; perder depresión escapular.', 'Dominá los fondos en paralelas antes de lastrar en anillas.', 'Añadí lastre solo cuando hacés 4x6 con anillas quietas.', 'Fondos en anillas a peso corporal.', array['Fondos con codos al cuerpo', 'Fondos con pausa'], array['Fondos en paralelas lastrados', 'Press banca agarre cerrado']),

('Flexiones lastradas', 'Weighted push-ups', 'push up con lastre', 'Accesorios Calistenia', 'Empuje', 'Flexiones', 'Accesorios Calistenia', 'Principiante', 2, 'Lastre (disco o chaleco)', 'Peso corporal', 'Compuesto', 'Empuje horizontal', array['Pectoral mayor'], array['Deltoides anterior', 'Tríceps braquial'], array['Core', 'Serrato anterior'], false, 'Cerrada', 'Fuerza', 4, '6-12', 120, 2, 'Flexión con carga sobre la espalda, excelente para hipertrofia de empuje con bajo costo de material.', 'Manos algo más anchas que hombros, cuerpo en línea. Bajá con codos a 45° y empujá sin perder el core.', 'Cadera alta o baja; abrir codos en cruz; recorrido parcial.', 'Colocá el disco de forma segura y usá chaleco si tenés.', 'Sumá reps y luego lastre hasta 4x10 con RIR 2.', 'Flexiones a peso corporal o inclinadas.', array['Flexiones declinadas', 'Flexiones arqueras', 'Flexiones diamante'], array['Press banca con barra', 'Fondos en paralelas']),

('Flexiones declinadas con lastre', 'Weighted decline push-ups', 'flexiones pies elevados', 'Accesorios Calistenia', 'Empuje', 'Flexiones', 'Accesorios Calistenia', 'Intermedio', 3, 'Cajón o banco y lastre', 'Peso corporal', 'Compuesto', 'Empuje vertical', array['Deltoides anterior'], array['Pectoral superior', 'Tríceps braquial'], array['Core', 'Serrato anterior'], false, 'Cerrada', 'Fuerza', 4, '6-12', 120, 2, 'Flexión con pies elevados que carga más el hombro, preparando pike push up y handstand.', 'Pies en un cajón, cuerpo en línea, manos bajo hombros. Bajá la cabeza al suelo y empujá.', 'Cadera descontrolada; rango parcial; perder el core.', 'Cuanto más alto el cajón, más carga de hombro: progresá de a poco.', 'Elevá los pies o sumá lastre al lograr 4x10.', 'Flexiones a peso corporal o pike push up.', array['Pike push up', 'Flexiones en pared'], array['Pike push up', 'Press militar con barra']),

('Flexiones arqueras lastradas', 'Weighted archer push-ups', 'archer push up con lastre', 'Accesorios Calistenia', 'Empuje', 'Flexiones', 'Accesorios Calistenia', 'Avanzado', 4, 'Lastre', 'Peso corporal', 'Compuesto', 'Empuje horizontal', array['Pectoral mayor'], array['Tríceps braquial', 'Deltoides anterior'], array['Core', 'Serrato anterior'], true, 'Cerrada', 'Fuerza', 4, '4-8', 120, 2, 'Flexión unilateral con el brazo de apoyo extendido; escalón clave hacia la flexión a una mano.', 'Manos anchas, un brazo se flexiona y el otro permanece casi recto. Bajá sobre el brazo que flexiona y empujá.', 'Rotar el torso; apoyar de más el brazo extendido; rango corto.', 'Cuidá el hombro y el codo del brazo de trabajo; progresá lento.', 'Lastrá o acercá la mano al centro al dominar 4x6 por lado.', 'Flexiones con manos muy abiertas o flexiones a una mano asistidas.', array['Flexiones a una mano asistidas'], array['Flexiones lastradas', 'Fondos en paralelas']),

('Pseudo planche push up con lastre', 'Weighted pseudo planche push-up', 'PPP con lastre, pseudoplancha', 'Accesorios Calistenia', 'Empuje', 'Planche', 'Accesorios Calistenia', 'Avanzado', 4, 'Lastre', 'Peso corporal', 'Compuesto', 'Empuje horizontal', array['Pectoral mayor (clavicular)'], array['Deltoides anterior', 'Tríceps braquial'], array['Serrato anterior', 'Core', 'Bíceps braquial'], false, 'Cerrada', 'Fuerza', 4, '5-8', 150, 2, 'Flexión con inclinación adelantada, el accesorio de fuerza que más transfiere a la planche.', 'Manos a la altura de la cintura con hombros muy por delante. Bajá manteniendo la inclinación y empujá sin perder el lean.', 'Perder el lean; cadera descontrolada; protracción insuficiente.', 'Calentá bien las muñecas; el estrés en hombro anterior es alto.', 'Más lean y luego lastre; objetivo 4x6 con RIR 2.', 'Pseudo planche push up a peso corporal o lean planche hold.', array['PPP con pausa', 'PPP a una mano'], array['Pseudo plancha isométrica', 'Press banca con barra']),

('Press de banca agarre cerrado', 'Close-grip bench press', 'press cerrado con barra', 'Accesorios Calistenia', 'Empuje', 'Empuje horizontal', 'Accesorios Calistenia', 'Intermedio', 2, 'Banco plano, barra y discos', 'Barra', 'Compuesto', 'Empuje horizontal', array['Tríceps braquial', 'Pectoral mayor'], array['Deltoides anterior'], array['Romboides', 'Serrato anterior'], false, 'Abierta', 'Fuerza', 4, '6-10', 150, 2, 'Press de banca con agarre estrecho que enfatiza tríceps, muy útil para bloquear dominadas y fondos.', 'Agarre a la altura de los hombros, omóplatos retraídos. Bajá al esternón con codos cerca y empujá.', 'Agarre demasiado angosto; abrir los codos; perder la retracción.', 'Cuidá las muñecas; no fuerces el agarre si molesta el codo.', 'Subí 2,5 kg al completar 4x8 con RIR 2.', 'Press francés o flexiones diamante.', array['Press agarre medio', 'Press con pausa'], array['Press francés con barra', 'Fondos en paralelas']),

('Dominadas lastradas', 'Weighted pull-ups', 'dominadas con lastre', 'Accesorios Calistenia', 'Tirón', 'Dominadas', 'Accesorios Calistenia', 'Intermedio', 3, 'Barra fija y lastre', 'Peso corporal', 'Compuesto', 'Tirón vertical', array['Dorsal ancho'], array['Bíceps braquial', 'Romboides', 'Trapecio'], array['Core', 'Antebrazo'], false, 'Cerrada', 'Fuerza', 4, '5-8', 150, 2, 'El accesorio de fuerza de tirón más directo; construye dorsales y brazos para skills y dominadas avanzadas.', 'Colgado con hombros activos, subí llevando el pecho a la barra sin balanceo y bajá controlado.', 'Usar impulso de piernas; no completar el rango; perder la depresión escapular.', 'Calentá codos y hombros; evitá si hay dolor de codo con agarre prono.', 'Añadí lastre al lograr 4x8 estrictas sin kipping.', 'Dominadas a peso corporal o asistidas con banda.', array['Dominadas con pausa', 'Dominadas supinas', 'Dominadas en anillas'], array['Jalón al pecho (no disponible)', 'Remo con barra']),

('Dominadas supinas lastradas', 'Weighted chin-ups', 'dominadas supinas con lastre', 'Accesorios Calistenia', 'Tirón', 'Dominadas', 'Accesorios Calistenia', 'Intermedio', 3, 'Barra fija y lastre', 'Peso corporal', 'Compuesto', 'Tirón vertical', array['Dorsal ancho', 'Bíceps braquial'], array['Romboides', 'Trapecio'], array['Core', 'Antebrazo'], false, 'Cerrada', 'Fuerza', 4, '5-8', 150, 2, 'Dominada con agarre supino que suma bíceps, ideal si el codo tolera mejor esta posición.', 'Agarre supino al ancho de hombros, subí llevando el pecho a la barra y bajá controlando.', 'Balanceo; rango parcial; perder el control del descenso.', 'Si molesta el codo, alterná con agarre neutro.', 'Añadí lastre al completar 4x8 estrictas.', 'Dominadas supinas a peso corporal o en anillas neutras.', array['Dominadas neutras', 'Dominadas a una mano asistidas'], array['Dominadas lastradas', 'Curl con barra']),

('Dominadas neutras en anillas lastradas', 'Weighted neutral ring pull-ups', 'dominadas neutras en anillas', 'Accesorios Calistenia', 'Tirón', 'Dominadas', 'Accesorios Calistenia', 'Intermedio', 3, 'Anillas y lastre', 'Peso corporal', 'Compuesto', 'Tirón vertical', array['Dorsal ancho', 'Braquial'], array['Bíceps braquial', 'Romboides'], array['Antebrazo', 'Core'], false, 'Cerrada', 'Fuerza', 4, '5-8', 150, 2, 'Dominada con agarre neutro en anillas, amable con codo y hombro y gran estímulo de dorsal.', 'Ánclate a las anillas, subí con agarre neutro llevando el pecho arriba y bajá con control.', 'Separar demasiado las anillas; usar balanceo; no extender del todo abajo.', 'Asegurá las anillas a la altura correcta antes de lastrar.', 'Sumá lastre al lograr 4x8 limpias.', 'Dominadas neutras a peso corporal.', array['Dominadas en anillas prono', 'Dominadas arqueras'], array['Dominadas lastradas', 'Remo en anillas']),

('Dominadas arqueras', 'Archer pull-ups', 'archer pull up', 'Accesorios Calistenia', 'Tirón', 'Dominadas', 'Accesorios Calistenia', 'Avanzado', 4, 'Barra fija', 'Peso corporal', 'Compuesto', 'Tirón vertical', array['Dorsal ancho'], array['Bíceps braquial', 'Romboides'], array['Core', 'Antebrazo'], true, 'Cerrada', 'Fuerza', 4, '4-8', 150, 2, 'Dominada unilateral asistida con un brazo extendido; escalón hacia la dominada a una mano.', 'Agarre ancho, subí cargando un lado mientras el otro brazo permanece casi recto, luego alterná.', 'No extender el brazo asistente; rango corto; perder el core.', 'Progresá lento por el estrés en codo y hombro del brazo de trabajo.', 'Acercá la mano al centro o sumá lastre al dominar 4x6 por lado.', 'Dominadas con agarre escalonado o a una mano asistidas.', array['Dominadas con toalla', 'Dominadas tipo arquero con pausa'], array['Dominadas lastradas', 'Remo en anillas']),

('Dominadas a una mano asistidas', 'Assisted one-arm pull-ups', 'one arm pull up asistida', 'Accesorios Calistenia', 'Tirón', 'Dominadas', 'Accesorios Calistenia', 'Elite', 5, 'Barra fija y toalla', 'Peso corporal', 'Compuesto', 'Tirón vertical', array['Dorsal ancho'], array['Bíceps braquial', 'Braquial'], array['Core', 'Antebrazo', 'Manguito rotador'], true, 'Cerrada', 'Fuerza', 5, '2-5', 180, 2, 'Progresión avanzada de tirón unilateral usando la otra mano como asistencia.', 'Sujetá la muñeca de trabajo en la barra y la otra mano en la propia muñeca o toalla; subí y bajá controlado.', 'Usar demasiada ayuda; balanceo; perder depresión escapular.', 'Alto estrés en codo y hombro: entrá con progresiones y buena recuperación.', 'Reducí la ayuda de la mano libre hasta lograr 5x3.', 'Dominadas arqueras o con agarre escalonado.', array['Dominadas con toalla', 'Dominadas negativas a una mano'], array['Dominadas arqueras', 'Dominadas lastradas']),

('Remo con barra', 'Barbell row', 'remo con barra inclinado', 'Accesorios Calistenia', 'Tirón', 'Remos', 'Accesorios Calistenia', 'Intermedio', 2, 'Barra y discos', 'Barra', 'Compuesto', 'Tirón horizontal', array['Dorsal ancho', 'Trapecio medio'], array['Romboides', 'Bíceps braquial', 'Deltoides posterior'], array['Erectores espinales', 'Core'], false, 'Cerrada', 'Hipertrofia', 4, '6-10', 120, 2, 'Remo pesado que construye espalda media y dorsales, base para front lever y remos fuertes.', 'Torso inclinado, espalda neutra, tirá la barra al abdomen bajo juntando escápulas y bajá controlado.', 'Redondear la espalda; tirar con brazos sin juntar escápulas; usar impulso.', 'Si la espalda baja molesta, usá inclinación menor o remo con apoyo.', 'Subí carga al completar 4x8 con RIR 2 y espalda neutra.', 'Remo con mancuerna a una mano o remo en anillas.', array['Remo Pendlay', 'Remo con agarre supino'], array['Remo en anillas', 'Remo con mancuerna a una mano']),

('Remo con mancuerna a una mano', 'Single-arm dumbbell row', 'remo con mancuerna', 'Accesorios Calistenia', 'Tirón', 'Remos', 'Accesorios Calistenia', 'Principiante', 1, 'Banco y mancuerna', 'Mancuernas', 'Compuesto', 'Tirón horizontal', array['Dorsal ancho'], array['Romboides', 'Bíceps braquial', 'Trapecio medio'], array['Core', 'Oblicuos'], true, 'Cerrada', 'Hipertrofia', 4, '8-12', 90, 2, 'Remo unilateral que corrige asimetrías y cuida la espalda baja al tener apoyo.', 'Mano y rodilla en el banco, espalda neutra. Tirá la mancuerna al costado juntando escápula.', 'Rotar el torso; tirar con el bíceps; redondear la espalda.', 'Fijate que el banco esté estable; evitá tirones bruscos.', 'Subí 1-2 kg al completar 4x10 RIR 2 por lado.', 'Remo en anillas con pies en el suelo.', array['Remo con agarre neutro', 'Remo a dos manos en banco'], array['Remo con barra', 'Remo en anillas']),

('Remo en anillas pies elevados lastrado', 'Weighted elevated ring rows', 'remo en anillas con lastre', 'Accesorios Calistenia', 'Tirón', 'Remos', 'Accesorios Calistenia', 'Intermedio', 3, 'Anillas y lastre', 'Peso corporal', 'Compuesto', 'Tirón horizontal', array['Dorsal ancho', 'Trapecio medio'], array['Romboides', 'Bíceps braquial'], array['Core', 'Glúteos'], false, 'Cerrada', 'Fuerza', 4, '6-10', 120, 2, 'Remo horizontal en anillas con pies elevados y lastre; gran transferencia a front lever y rows avanzados.', 'Cuerpo rígido y horizontal, tirá del pecho hacia las anillas juntando escápulas y bajá controlado.', 'Caderas caídas; rango parcial; no juntar escápulas.', 'Asegurá el lastre para que no se mueva durante el remo.', 'Elevá los pies o sumá lastre al lograr 4x10.', 'Remo en anillas con pies en el suelo.', array['Remo en anillas con pausa', 'Remo tipo front lever'], array['Remo con barra', 'Dominadas lastradas']),

('Remo invertido en barra lastrado', 'Weighted inverted rows', 'remo invertido', 'Accesorios Calistenia', 'Tirón', 'Remos', 'Accesorios Calistenia', 'Principiante', 2, 'Barra baja y lastre', 'Peso corporal', 'Compuesto', 'Tirón horizontal', array['Dorsal ancho'], array['Romboides', 'Bíceps braquial', 'Trapecio'], array['Core', 'Glúteos'], false, 'Cerrada', 'Fuerza', 4, '8-12', 90, 2, 'Remo bajo la barra con lastre, accesible y muy útil como base de tirón horizontal.', 'Colgado bajo la barra con cuerpo recto, tirá el pecho a la barra y bajá con control.', 'Cadera caída; subir solo la cabeza; rango parcial.', 'Asegurá la barra a una altura estable para los pies.', 'Elevá los pies en un cajón o sumá lastre al dominar 4x12.', 'Remo en barra alta o remo en anillas.', array['Remo invertido agarre supino', 'Remo invertido a una mano'], array['Remo en anillas', 'Remo con mancuerna a una mano']),

('Pull-over con barra', 'Barbell pull-over', 'pull over', 'Accesorios Calistenia', 'Tirón', 'Accesorios de tirón', 'Accesorios Calistenia', 'Intermedio', 2, 'Banco plano, barra y discos', 'Barra', 'Aislado', 'Flexión de hombro', array['Dorsal ancho', 'Pectoral mayor'], array['Tríceps braquial (cabeza larga)', 'Serrato anterior'], array['Core', 'Romboides'], false, 'Abierta', 'Hipertrofia', 3, '10-15', 90, 2, 'Trabaja el dorsal en su función de flexión de hombro, aportando fuerza al inicio de dominadas y front lever.', 'Acostado, brazos casi rectos, bajá la barra por detrás de la cabeza sintiendo el estiramiento y volvé.', 'Doblar demasiado los codos; usar demasiado peso; forzar el hombro.', 'Empezá liviano; cuidá el hombro si hay molestias.', 'Subí carga al completar 3x12 con control.', 'Pull-over con mancuerna en el suelo.', array['Pull-over con mancuerna', 'Pull-over en anillas'], array['Remo en anillas', 'Dominadas lastradas']),

('Remo al mentón con barra', 'Barbell upright row', 'remo al mentón', 'Accesorios Calistenia', 'Tirón', 'Accesorios de tirón', 'Accesorios Calistenia', 'Intermedio', 2, 'Barra y discos', 'Barra', 'Aislado', 'Elevación', array['Deltoides anterior', 'Trapecio'], array['Bíceps braquial', 'Deltoides lateral'], array['Romboides'], false, 'Abierta', 'Hipertrofia', 3, '10-15', 90, 2, 'Trabaja trapecio y deltoides en elevación, útil para estabilidad de hombro en anillas.', 'De pie, subí la barra pegada al cuerpo hasta el mentón llevando codos hacia arriba y bajá controlado.', 'Subir demasiado; usar impulso; rotar el hombro en forma agresiva.', 'Si molesta el hombro, limitá la altura o usá mancuernas.', 'Subí reps y luego carga manteniendo 3x12 RIR 2.', 'Elevaciones laterales o pájaros.', array['Remo al mentón con mancuernas', 'Remo al mentón agarre ancho'], array['Elevaciones laterales con mancuernas', 'Pájaros con mancuernas']),

('Front lever raises lastradas', 'Weighted front lever raises', 'raises de front lever', 'Accesorios Calistenia', 'Tirón', 'Front lever', 'Accesorios Calistenia', 'Avanzado', 4, 'Barra fija y lastre', 'Peso corporal', 'Compuesto', 'Tirón horizontal', array['Dorsal ancho', 'Core'], array['Romboides', 'Bíceps braquial'], array['Core', 'Glúteos'], false, 'Cerrada', 'Fuerza', 4, '4-8', 150, 2, 'Desde colgado, elevá el cuerpo a front lever y bajá con control; accesorio específico de fuerza de front lever.', 'Cuerpo rígido, subí a la posición de front lever (aunque sea tuck) manteniendo escápulas deprimidas y bajá lento.', 'Caderas caídas; balanceo; perder la línea del cuerpo.', 'Alto estrés de hombro y codo; calentá y progresá por niveles.', 'Extendé las piernas o sumá lastre al controlar 4x6.', 'Front lever tuck raises o negativas de front.', array['Raises con pausa', 'Raises en anillas'], array['Front lever tuck holds', 'Remo en anillas']),

('Back lever raises lastradas', 'Weighted back lever raises', 'raises de back lever', 'Accesorios Calistenia', 'Tirón', 'Back lever', 'Accesorios Calistenia', 'Avanzado', 4, 'Barra fija y lastre', 'Peso corporal', 'Compuesto', 'Tirón horizontal', array['Dorsal ancho', 'Pectoral mayor'], array['Deltoides posterior', 'Bíceps braquial'], array['Core', 'Glúteos'], false, 'Cerrada', 'Fuerza', 4, '4-8', 150, 2, 'Elevación del cuerpo a back lever con control, accesorio específico de fuerza de back lever.', 'Desde inverted hang, bajá a back lever manteniendo brazos rectos y cuerpo firme, luego subí controlado.', 'Doblar codos; perder la línea; caer brusco.', 'Progresá por tuck/straddle antes de lastrar.', 'Sumá lastre cuando controlás 4x6 con brazos rectos.', 'Negativas de back lever o tuck holds.', array['Raises con pausa', 'Back lever en anillas'], array['Front lever raises lastradas', 'Remo en anillas']),

('Elevaciones laterales con mancuernas', 'Dumbbell lateral raise', 'laterales con mancuernas', 'Accesorios Calistenia', 'Hombros', 'Deltoides', 'Accesorios Calistenia', 'Principiante', 1, 'Mancuernas', 'Mancuernas', 'Aislado', 'Abducción', array['Deltoides lateral'], array['Trapecio', 'Supraespinoso'], array['Core'], false, 'Abierta', 'Hipertrofia', 4, '12-15', 60, 1, 'Aísla el deltoides lateral; hombros más anchos y estables ayudan a la estética y a la planche.', 'Codos ligeramente flexionados, subí hasta la línea del hombro y bajá controlado sin balanceo.', 'Usar impulso; subir por encima del hombro; encoger trapecios.', 'Cargas livianas, técnica primero; evitá si duele el hombro.', 'Subí reps y luego 0,5-1 kg manteniendo 4x15.', 'Elevaciones laterales sentado o parciales.', array['Laterales inclinado al banco', 'Laterales con pausa'], array['Elevaciones frontales', 'Press militar con mancuernas']),

('Elevaciones laterales inclinado en banco', 'Incline lateral raise', 'laterales acostado inclinado', 'Accesorios Calistenia', 'Hombros', 'Deltoides', 'Accesorios Calistenia', 'Intermedio', 2, 'Banco inclinado y mancuerna', 'Mancuernas', 'Aislado', 'Abducción', array['Deltoides lateral'], array['Supraespinoso', 'Trapecio'], array['Core'], true, 'Abierta', 'Hipertrofia', 3, '12-15', 60, 1, 'Variante que elimina el impulso y aumenta el rango efectivo del deltoides lateral.', 'Apoyado de costado en banco inclinado, subí la mancuerna hasta arriba con codo algo flexionado y bajá lento.', 'Rotar el torso; usar impulso; rango corto.', 'Usá cargas livianas; controlá el hombro en todo el rango.', 'Subí reps o carga manteniendo 3x15 con control.', 'Laterales de pie con mancuernas.', array['Laterales acostado en el suelo', 'Laterales con pausa'], array['Elevaciones laterales con mancuernas', 'Pájaros con mancuernas']),

('Pájaros con mancuernas', 'Bent-over dumbbell reverse fly', 'pájaros, reverse fly', 'Accesorios Calistenia', 'Hombros', 'Deltoides posterior', 'Accesorios Calistenia', 'Principiante', 1, 'Mancuernas', 'Mancuernas', 'Aislado', 'Abducción', array['Deltoides posterior'], array['Romboides', 'Trapecio medio'], array['Erectores espinales', 'Core'], false, 'Abierta', 'Hipertrofia', 4, '12-15', 60, 1, 'Deltoides posterior y espalda alta; clave para balancear el empuje y proteger el hombro.', 'Torso inclinado, espalda neutra. Abrí los brazos con codos algo flexionados y juntá las escápulas.', 'Usar impulso; encoger el cuello; doblar demasiado los codos.', 'Mantené la espalda neutra durante todo el set.', 'Subí reps y luego carga manteniendo 4x15.', 'Pájaros sentado con pecho apoyado.', array['Pájaros en banco inclinado', 'Pájaros con pausa'], array['Face pull acostado con mancuernas', 'Y-raise en banco inclinado']),

('Elevación frontal con mancuernas', 'Dumbbell front raise', 'frontales con mancuernas', 'Accesorios Calistenia', 'Hombros', 'Deltoides anterior', 'Accesorios Calistenia', 'Principiante', 1, 'Mancuernas', 'Mancuernas', 'Aislado', 'Flexión de hombro', array['Deltoides anterior'], array['Pectoral superior'], array['Core', 'Serrato anterior'], true, 'Abierta', 'Hipertrofia', 3, '12-15', 60, 1, 'Aísla el deltoides anterior, útil para completar el desarrollo del hombro de empuje.', 'De pie, subí la mancuerna al frente hasta la altura del hombro con codo casi recto y bajá controlado.', 'Balancear el torso; subir por encima del hombro; encoger trapecio.', 'Evitá cargas altas; el deltoides anterior ya trabaja en press.', 'Subí reps y luego carga manteniendo 3x15.', 'Elevación frontal con barra liviana.', array['Frontal con pausa', 'Frontal agarre neutro'], array['Elevaciones laterales con mancuernas', 'Press militar con mancuernas']),

('Press Arnold con mancuernas', 'Arnold press', 'press arnold', 'Accesorios Calistenia', 'Hombros', 'Press de hombros', 'Accesorios Calistenia', 'Intermedio', 2, 'Mancuernas y banco con respaldo', 'Mancuernas', 'Compuesto', 'Empuje vertical', array['Deltoides anterior'], array['Deltoides lateral', 'Tríceps braquial'], array['Serrato anterior', 'Romboides'], false, 'Abierta', 'Hipertrofia', 4, '8-12', 120, 2, 'Press con rotación que recorre anterior y lateral del deltoides en un solo movimiento.', 'Empezá con mancuernas frente al pecho y palmas hacia vos; rotá mientras empujás arriba y volvé igual.', 'Arquear la lumbar; rotar de golpe; perder el control del descenso.', 'Usá un peso que puedas controlar en la rotación.', 'Subí reps y luego carga manteniendo 4x10 RIR 2.', 'Press sentado con mancuernas.', array['Arnold a una mano', 'Arnold con pausa'], array['Press militar sentado con mancuernas', 'Press militar con barra']),

('Y-raise en banco inclinado', 'Incline Y-raise', 'Y raise', 'Accesorios Calistenia', 'Hombros', 'Deltoides posterior', 'Accesorios Calistenia', 'Intermedio', 2, 'Banco inclinado y mancuernas livianas', 'Mancuernas', 'Aislado', 'Elevación escapular', array['Deltoides posterior', 'Trapecio inferior'], array['Romboides', 'Supraespinoso'], array['Core'], false, 'Abierta', 'Control corporal', 3, '12-15', 60, 1, 'Trabaja trapecio inferior y deltoides posterior, fundamental para la salud del hombro en anillas.', 'Pecho apoyado en banco inclinado, subí los brazos en forma de Y con pulgares arriba y bajá lento.', 'Encoger el cuello; usar impulso; subir con carga excesiva.', 'Cargas muy livianas; priorizá la sensación escapular.', 'Aumentá reps y luego 0,5 kg manteniendo 3x15.', 'Y-raise en el suelo boca abajo.', array['Y-raise con pausa', 'Y-raise en anillas'], array['Pájaros con mancuernas', 'Wall slide con elevación']),

('Rotación externa con mancuerna acostado', 'Side-lying external rotation', 'rotación externa tumbado', 'Accesorios Calistenia', 'Hombros', 'Manguito rotador', 'Accesorios Calistenia', 'Principiante', 1, 'Mancuerna liviana', 'Mancuernas', 'Estabilidad', 'Rotación externa', array['Infraespinoso', 'Redondo menor'], array['Deltoides posterior'], array['Core'], true, 'Abierta', 'Control corporal', 3, '12-15', 60, 2, 'Fortalece el manguito rotador, prevención clave para el hombro que exige la calistenia.', 'Acostado de costado, codo a 90° pegado al cuerpo. Rotá la mancuerna hacia arriba y bajá lento.', 'Separar el codo del cuerpo; usar impulso; cargas altas.', 'Peso liviano; es un ejercicio de control, no de fuerza máxima.', 'Subí reps o 0,5 kg manteniendo 3x15 con control.', 'Rotación externa sin peso o con banda liviana.', array['Rotación externa en 90°', 'Rotación externa con pausa'], array['Rotación externa a 90° (cuban)', 'Face pull acostado con mancuernas']),

('Rotación externa a 90° (cuban press)', 'Cuban press', 'cuban rotation, rotación 90 grados', 'Accesorios Calistenia', 'Hombros', 'Manguito rotador', 'Accesorios Calistenia', 'Intermedio', 2, 'Mancuernas livianas', 'Mancuernas', 'Estabilidad', 'Rotación externa', array['Infraespinoso', 'Redondo menor'], array['Deltoides posterior', 'Trapecio inferior'], array['Romboides'], false, 'Abierta', 'Control corporal', 3, '10-12', 60, 2, 'Rotación externa a 90° de hombro que fortalece el manguito en la posición más exigente.', 'Codos a 90° y hombros elevados; rotá hasta que las manos apunten arriba y luego empujá a extensión.', 'Bajar los codos; rotar de golpe; usar cargas altas.', 'Progresá muy lento; es un ejercicio preventivo, no de carga.', 'Aumentá reps o mínimo peso manteniendo 3x12.', 'Rotación externa acostado de costado.', array['Cuban press con barra liviana', 'Cuban press parcial'], array['Rotación externa con mancuerna acostado', 'Face pull acostado con mancuernas']),

('Rotación interna con mancuerna', 'Dumbbell internal rotation', 'rotación interna', 'Accesorios Calistenia', 'Hombros', 'Manguito rotador', 'Accesorios Calistenia', 'Principiante', 1, 'Mancuerna liviana', 'Mancuernas', 'Estabilidad', 'Rotación interna', array['Subescapular'], array['Pectoral mayor', 'Dorsal ancho'], array['Core'], true, 'Abierta', 'Control corporal', 3, '12-15', 60, 2, 'Complementa el trabajo del manguito fortaleciendo el subescapular y equilibrando el hombro.', 'Acostado de costado, codo a 90° pegado al torso. Llevá la mancuerna hacia el abdomen y volvé lento.', 'Mover el codo; usar impulso; cargas altas.', 'Peso liviano; control total del movimiento.', 'Subí reps o 0,5 kg manteniendo 3x15.', 'Rotación interna sin peso.', array['Rotación interna con pausa', 'Rotación interna con banda liviana'], array['Rotación externa con mancuerna acostado', 'Cuban press']),

('Face pull acostado con mancuernas', 'Prone face pull with dumbbells', 'face pull con mancuernas', 'Accesorios Calistenia', 'Hombros', 'Deltoides posterior', 'Accesorios Calistenia', 'Principiante', 1, 'Banco inclinado y mancuernas', 'Mancuernas', 'Estabilidad', 'Tirón horizontal', array['Deltoides posterior', 'Trapecio medio'], array['Romboides', 'Infraespinoso'], array['Core'], false, 'Abierta', 'Control corporal', 3, '12-15', 60, 1, 'Alternativa al face pull de polea que trabaja deltoides posterior y manguito sin equipamiento guiado.', 'Pecho apoyado en banco inclinado, tirá las mancuernas hacia la cara abriendo codos y juntando escápulas.', 'Encoger el cuello; tirar solo con brazos; rango corto.', 'Cargas livianas y movimiento controlado.', 'Subí reps y luego peso manteniendo 3x15.', 'Pájaros con mancuernas.', array['Face pull con pausa', 'Face pull a una mano'], array['Pájaros con mancuernas', 'Y-raise en banco inclinado']),

('Curl con barra', 'Barbell curl', 'curl de bíceps con barra', 'Accesorios Calistenia', 'Bíceps', 'Curl bíceps', 'Accesorios Calistenia', 'Principiante', 1, 'Barra y discos', 'Barra', 'Aislado', 'Flexión de codo', array['Bíceps braquial'], array['Braquial', 'Braquiorradial'], array['Core', 'Deltoides anterior'], false, 'Abierta', 'Hipertrofia', 4, '8-12', 90, 1, 'Constructor principal de bíceps; más fuerza de flexión ayuda en dominadas y front lever.', 'De pie, codos pegados al torso, subí la barra sin balanceo y bajá controlando la fase excéntrica.', 'Balancear el cuerpo; abrir los codos; rango parcial.', 'Evitá si molesta la muñeca; probá barra EZ.', 'Subí 1-2 kg al completar 4x12 con RIR 1.', 'Curl con mancuernas o curl en anillas.', array['Curl con barra EZ', 'Curl 21s', 'Curl con pausa'], array['Curl con mancuernas', 'Curl en anillas a una mano']),

('Curl con mancuernas', 'Dumbbell curl', 'curl alterno', 'Accesorios Calistenia', 'Bíceps', 'Curl bíceps', 'Accesorios Calistenia', 'Principiante', 1, 'Mancuernas', 'Mancuernas', 'Aislado', 'Flexión de codo', array['Bíceps braquial'], array['Braquial', 'Braquiorradial'], array['Core'], true, 'Abierta', 'Hipertrofia', 4, '10-12', 90, 1, 'Curl unilateral que permite supinar y corregir diferencias entre brazos.', 'Codo fijo al costado, subí la mancuerna supinando y bajá lento hasta extensión.', 'Balanceo; subir el codo; no extender del todo.', 'Controlá el descenso para maximizar estímulo.', 'Subí 1 kg por mancuerna al completar 4x12.', 'Curl alterno o curl martillo.', array['Curl alterno', 'Curl supino', 'Curl con pausa isométrica'], array['Curl con barra', 'Curl en anillas a una mano']),

('Curl martillo', 'Hammer curl', 'curl neutro', 'Accesorios Calistenia', 'Bíceps', 'Braquial / braquiorradial', 'Accesorios Calistenia', 'Principiante', 1, 'Mancuernas', 'Mancuernas', 'Aislado', 'Flexión de codo', array['Braquial', 'Braquiorradial'], array['Bíceps braquial'], array['Core', 'Antebrazo'], true, 'Abierta', 'Hipertrofia', 4, '10-12', 90, 1, 'Agarre neutro que enfatiza braquial y braquiorradial, aumentando el grosor del brazo.', 'Codo fijo, subí la mancuerna con pulgar arriba sin rotar y bajá controlado.', 'Balanceo; mover el codo; rango corto.', 'Muy amable con el codo; buena opción si el curl supino molesta.', 'Subí carga al completar 4x12 con control.', 'Curl martillo con barra o con toalla.', array['Curl martillo cruzado', 'Curl martillo con pausa'], array['Curl con mancuernas', 'Curl de dedos con barra']),

('Curl inclinado en banco', 'Incline dumbbell curl', 'curl inclinado', 'Accesorios Calistenia', 'Bíceps', 'Curl bíceps (cabeza larga)', 'Accesorios Calistenia', 'Intermedio', 2, 'Banco inclinado y mancuernas', 'Mancuernas', 'Aislado', 'Flexión de codo', array['Bíceps braquial (cabeza larga)'], array['Braquial'], array['Deltoides anterior'], true, 'Abierta', 'Hipertrofia', 3, '10-12', 90, 1, 'Con el brazo detrás del cuerpo, estira la cabeza larga del bíceps y maximiza el rango.', 'Sentado en banco inclinado con brazos colgando atrás; subí sin mover el codo y bajá lento.', 'Adelantar el codo; usar impulso; rango parcial.', 'Cuidá el codo por el estiramiento profundo; empezá liviano.', 'Subí 1 kg al completar 3x12 con control.', 'Curl sentado con mancuernas.', array['Curl inclinado neutro', 'Curl inclinado con pausa'], array['Curl con mancuernas', 'Curl predicador con barra']),

('Curl predicador con barra', 'Preacher curl', 'curl araña, curl predicador', 'Accesorios Calistenia', 'Bíceps', 'Curl bíceps', 'Accesorios Calistenia', 'Intermedio', 2, 'Banco predicador, barra EZ', 'Barra', 'Aislado', 'Flexión de codo', array['Bíceps braquial'], array['Braquial'], array['Deltoides anterior'], false, 'Abierta', 'Hipertrofia', 3, '10-12', 90, 1, 'Con el brazo fijo en el soporte, aísla el bíceps y evita el balanceo.', 'Axilas apoyadas en el banco, subí la barra hasta casi tocar el hombro y bajá controlando la extensión.', 'Levantar los codos del soporte; no extender; usar impulso.', 'No busques la extensión máxima con cargas altas; cuidá el codo.', 'Subí carga al completar 3x12 con control.', 'Curl con mancuernas sobre banco inclinado.', array['Curl predicador a una mano', 'Curl predicador en anillas'], array['Curl inclinado en banco', 'Curl con barra']),

('Curl concentrado', 'Concentration curl', 'curl concentrado', 'Accesorios Calistenia', 'Bíceps', 'Curl bíceps', 'Accesorios Calistenia', 'Principiante', 1, 'Banco y mancuerna', 'Mancuernas', 'Aislado', 'Flexión de codo', array['Bíceps braquial'], array['Braquial'], array['Core'], true, 'Abierta', 'Hipertrofia', 3, '10-12', 60, 1, 'Curl apoyado en el muslo que maximiza la conexión mente-músculo del bíceps.', 'Sentado, codo apoyado en el muslo; subí la mancuerna hasta el hombro y bajá lento.', 'Mover el codo; usar impulso; rango corto.', 'Buena opción para trabajo de aislamiento y corrección de asimetrías.', 'Subí 0,5-1 kg al completar 3x12.', 'Curl sentado con mancuernas.', array['Curl concentrado con supinación', 'Curl concentrado isométrico'], array['Curl con mancuernas', 'Curl predicador con barra']),

('Curl en anillas a una mano', 'One-arm ring curl', 'curl en anillas', 'Accesorios Calistenia', 'Bíceps', 'Curl bíceps', 'Accesorios Calistenia', 'Intermedio', 2, 'Anillas', 'Peso corporal', 'Aislado', 'Flexión de codo', array['Bíceps braquial'], array['Braquial', 'Antebrazo'], array['Core', 'Manguito rotador'], true, 'Cerrada', 'Hipertrofia', 3, '8-12', 90, 1, 'Curl en anillas con inclinación del cuerpo, muy específico para el tirón calisténico.', 'Sujetá una anilla, incliná el cuerpo atrás y flexioná el codo llevando la anilla al hombro; bajá controlado.', 'Perder la tensión del cuerpo; mover el codo; rango parcial.', 'Ajustá la inclinación para regular la dificultad.', 'Aumentá la inclinación o hacelo a una sola anilla con menos cuerpo.', 'Curl en anillas con el cuerpo más vertical.', array['Curl en anillas a dos manos', 'Curl en anillas neutro'], array['Curl con mancuernas', 'Dominadas supinas lastradas']),

('Press francés con barra', 'Lying triceps extension', 'press francés, skull crusher', 'Accesorios Calistenia', 'Tríceps', 'Extensiones', 'Accesorios Calistenia', 'Intermedio', 2, 'Banco plano y barra EZ', 'Barra', 'Aislado', 'Extensión de codo', array['Tríceps braquial'], array['Ancóneo'], array['Core', 'Deltoides anterior'], false, 'Abierta', 'Hipertrofia', 4, '8-12', 90, 1, 'Aislamiento clásico de tríceps que da fuerza de bloqueo para fondos, planche y press a pino.', 'Acostado, brazos verticales, bajá la barra hacia la frente doblando solo los codos y extendé.', 'Abrir los codos; mover el hombro; golpear la frente.', 'Cuidá los codos; evitá cargas altas con dolor.', 'Subí 1-2 kg al completar 4x12 con control.', 'Extensión sobre la cabeza con mancuerna.', array['Press francés a una mano', 'Press francés con pausa'], array['Extensión de tríceps sobre la cabeza con mancuerna', 'Fondos en banco']),

('Extensión de tríceps sobre la cabeza con mancuerna', 'Overhead dumbbell triceps extension', 'extensión sobre cabeza', 'Accesorios Calistenia', 'Tríceps', 'Extensiones (cabeza larga)', 'Accesorios Calistenia', 'Principiante', 1, 'Mancuerna y banco', 'Mancuernas', 'Aislado', 'Extensión de codo', array['Tríceps braquial (cabeza larga)'], array['Ancóneo'], array['Core', 'Deltoides anterior'], false, 'Abierta', 'Hipertrofia', 3, '10-12', 90, 1, 'Con el brazo por encima de la cabeza, estira la cabeza larga del tríceps, mejorando el rango.', 'Sentado o acostado, sujetá la mancuerna con ambas manos, bajá por detrás de la cabeza y extendé.', 'Abrir los codos; arquear la espalda; rango parcial.', 'Controlá el codo; empezá liviano por el rango profundo.', 'Subí 1 kg al completar 3x12 con control.', 'Extensión con una mancuerna a dos manos.', array['Extensión sentado', 'Extensión acostado'], array['Press francés con barra', 'Patada de tríceps con mancuerna']),

('Patada de tríceps con mancuerna', 'Dumbbell kickback', 'patada de tríceps', 'Accesorios Calistenia', 'Tríceps', 'Extensiones', 'Accesorios Calistenia', 'Principiante', 1, 'Mancuerna y banco', 'Mancuernas', 'Aislado', 'Extensión de codo', array['Tríceps braquial'], array['Ancóneo'], array['Core', 'Dorsal ancho'], true, 'Abierta', 'Hipertrofia', 3, '12-15', 60, 1, 'Extensión con el brazo paralelo al suelo que aísla el tríceps con muy poca carga.', 'Torso inclinado con apoyo, codo alto y fijo; extendé el brazo hacia atrás y volvé lento.', 'Bajar el codo; usar impulso; no completar la extensión.', 'Cargas livianas y control; buen ejercicio de bombeo.', 'Subí 0,5-1 kg al completar 3x15.', 'Patada de tríceps con mancuerna liviana o sin peso.', array['Patada a una mano con pausa', 'Patada con barra liviana'], array['Press francés con barra', 'Extensión de tríceps sobre la cabeza con mancuerna']),

('Fondos en banco', 'Bench dips', 'fondos en banco', 'Accesorios Calistenia', 'Tríceps', 'Fondos cerrados', 'Accesorios Calistenia', 'Principiante', 1, 'Banco', 'Peso corporal', 'Compuesto', 'Extensión de codo', array['Tríceps braquial'], array['Pectoral mayor', 'Deltoides anterior'], array['Romboides'], false, 'Cerrada', 'Hipertrofia', 3, '10-15', 90, 1, 'Fondos con pies apoyados, accesibles para hipertrofia de tríceps y base para fondos en paralelas.', 'Manos en el borde del banco, codos detrás; bajá hasta 90° y empujá sin perder los hombros abajo.', 'Bajar demasiado; hombros elevados; alejar el cuerpo del banco.', 'Si molesta el hombro anterior, limitá el rango.', 'Elevá los pies o sumá lastre al completar 3x15.', 'Fondos con pies en el suelo y poco rango.', array['Fondos en banco lastrados', 'Fondos en banco a una pierna'], array['Fondos en paralelas lastrados', 'Press de banca agarre cerrado']),

('Flexiones diamante lastradas', 'Weighted diamond push-ups', 'flexiones diamante, triceps push up', 'Accesorios Calistenia', 'Tríceps', 'Fondos cerrados', 'Accesorios Calistenia', 'Intermedio', 2, 'Lastre', 'Peso corporal', 'Compuesto', 'Empuje horizontal', array['Tríceps braquial', 'Pectoral mayor'], array['Deltoides anterior'], array['Core', 'Serrato anterior'], false, 'Cerrada', 'Hipertrofia', 4, '8-12', 90, 1, 'Flexión con manos juntas que enfatiza tríceps; el accesorio de empuje cerrado sin material.', 'Manos formando un diamante bajo el pecho, cuerpo en línea. Bajá con codos cerca y empujá.', 'Codos abiertos; cadera descontrolada; rango parcial.', 'Cuidá las muñecas; si molesta, usá puños o paralelas.', 'Sumá lastre al completar 4x12.', 'Flexiones con manos juntas a peso corporal.', array['Flexiones diamante con pies elevados', 'Flexiones diamante a una mano'], array['Press de banca agarre cerrado', 'Fondos en paralelas']),

('Extensiones de tríceps en anillas', 'Ring triceps extensions', 'triceps extension en anillas', 'Accesorios Calistenia', 'Tríceps', 'Extensiones', 'Accesorios Calistenia', 'Intermedio', 2, 'Anillas', 'Peso corporal', 'Aislado', 'Extensión de codo', array['Tríceps braquial'], array['Ancóneo'], array['Core', 'Manguito rotador'], false, 'Cerrada', 'Hipertrofia', 3, '8-12', 90, 1, 'Extensión en anillas que suma inestabilidad y exige control escapular.', 'En apoyo o de rodillas frente a las anillas, brazos fijos, bajá la cabeza doblando codos y extendé.', 'Abrir los codos; perder la posición de hombro; rango corto.', 'Asegurá las anillas; progresá desde rodillas.', 'Pasá a apoyo completo o sumá lastre al dominar 3x12.', 'Extensiones de tríceps en anillas de rodillas.', array['Extensiones en anillas con pies elevados', 'Extensiones en anillas lastradas'], array['Press francés con barra', 'Fondos en paralelas lastrados']),

('Press cerrado con barra', 'Close-grip bench press', 'press cerrado', 'Accesorios Calistenia', 'Tríceps', 'Fondos cerrados', 'Accesorios Calistenia', 'Intermedio', 2, 'Banco plano, barra y discos', 'Barra', 'Compuesto', 'Empuje horizontal', array['Tríceps braquial', 'Pectoral mayor'], array['Deltoides anterior'], array['Romboides', 'Serrato anterior'], false, 'Abierta', 'Fuerza', 4, '6-10', 150, 2, 'Press de banca con agarre estrecho para fuerza de tríceps, complemento directo del empuje en fondos.', 'Agarre al ancho de hombros, omóplatos retraídos; bajá al esternón con codos cerca y empujá fuerte.', 'Agarre demasiado cerrado; abrir codos; perder retracción.', 'Cuidá muñecas y codos con cargas altas.', 'Subí 2,5 kg al completar 4x8 con RIR 2.', 'Press francés o flexiones diamante.', array['Press cerrado con pausa', 'Press cerrado con mancuernas'], array['Press francés con barra', 'Fondos en paralelas lastrados'])

on conflict (nombre, disciplina) do nothing;

-- ============================================================
-- VERIFICACION
-- ============================================================
do $acc_verif$
declare v_total int; v_rev int; v_dup int;
begin
  select count(*) into v_total from public.exercises where disciplina = 'Accesorios Calistenia';
  select count(*) into v_rev   from public.exercises where disciplina = 'Accesorios Calistenia' and coalesce(estado_clasificacion,'') = 'a_revisar';
  select count(*) into v_dup   from public.exercises where disciplina = 'Accesorios Calistenia' and duplicado_de is not null;
  raise notice 'ACCESORIOS OK · total=% · a_revisar=% · duplicados=%', v_total, v_rev, v_dup;
end
$acc_verif$;

-- Conteo por categoria (para copiar al chat)
select categoria, count(*) as total
from public.exercises
where disciplina = 'Accesorios Calistenia'
group by categoria
order by total desc, categoria;
