-- ============================================================
-- ATLETIX · Biblioteca de ACCESORIOS DE CALISTENIA · LOTE 2 (64 ejercicios)
-- Antebrazos / Core / Piernas / Agarre / Prehabilitación / Cuerpo completo / Movilidad
-- Requiere 0022. Idempotente: on conflict (nombre, disciplina) do nothing.
-- ============================================================

-- LOTE 2 · Antebrazos / Core / Piernas / Agarre / Prehabilitación / Cuerpo completo / Movilidad

insert into public.exercises
  (nombre, nombre_en, aliases, disciplina, categoria, subcategoria, tipo, dificultad, nivel_dificultad,
   equipamiento, tipo_resistencia, tipo_ejercicio, patron, musculos_primarios, musculos_secundarios,
   musculos_estabilizadores, unilateral, cadena_cinetica, objetivo, series_sugeridas, reps_sugeridas,
   descanso_seg, rir_sugerido, descripcion, instrucciones, errores_comunes, precauciones,
   criterio_progresion, regresion, variantes, sustitutos)
values
('Curl de muñeca con barra', 'Barbell wrist curl', 'flexión de muñeca con barra, curl de muñeca', 'Accesorios Calistenia', 'Antebrazos', 'Flexores de muñeca', 'Accesorios Calistenia', 'Principiante', 1, 'Banco, barra y discos', 'Barra', 'Aislado', 'Trabajo de agarre', array['Flexores de muñeca'], array['Flexor superficial de los dedos', 'Palmar largo'], array['Core'], false, 'Abierta', 'Hipertrofia', 3, '15-20', 45, 1, 'Trabajo directo de los flexores de muñeca, clave para un agarre fuerte en colgados y dominadas.', 'Sentado con antebrazos apoyados en los muslos y muñecas al borde, dejá bajar la barra y flexioná cerrando las manos.', 'Mover los codos; usar recorrido corto; balancear el cuerpo.', 'Empezá liviano; la muñeca tolera poca carga en rangos extremos.', 'Subí 1-2 kg al completar 3x20 con control.', 'Curl de muñeca con mancuernas livianas.', array['Curl de muñeca con pausa', 'Curl de muñeca a una mano'], array['Curl de muñeca con mancuernas', 'Curl de dedos con barra']),

('Extensión de muñeca con barra', 'Barbell wrist extension', 'extensión de muñeca con barra, extensores de muñeca', 'Accesorios Calistenia', 'Antebrazos', 'Extensores de muñeca', 'Accesorios Calistenia', 'Principiante', 1, 'Banco, barra y discos', 'Barra', 'Aislado', 'Trabajo de agarre', array['Extensores de muñeca'], array['Braquiorradial'], array['Core'], false, 'Abierta', 'Hipertrofia', 3, '15-20', 45, 1, 'Fortalece los extensores de muñeca y equilibra el trabajo de flexores, previniendo molestias de codo.', 'Antebrazos apoyados con las manos hacia abajo; subí la barra extendiendo la muñeca y bajá lento.', 'Levantar los antebrazos; usar impulso; rango parcial.', 'Carga muy liviana; priorizá el control sobre el peso.', 'Subí 1 kg al completar 3x20 sin dolor.', 'Extensión de muñeca con mancuernas livianas.', array['Extensión de muñeca con pausa', 'Extensión unilateral'], array['Extensión de muñeca con mancuernas', 'Curl inverso con barra']),

('Curl inverso con barra', 'Reverse barbell curl', 'curl prono, reverse curl', 'Accesorios Calistenia', 'Antebrazos', 'Braquiorradial', 'Accesorios Calistenia', 'Principiante', 1, 'Barra recta o Z', 'Barra', 'Aislado', 'Flexión de codo', array['Braquiorradial'], array['Braquial', 'Extensores de muñeca'], array['Core'], false, 'Abierta', 'Hipertrofia', 3, '10-12', 60, 1, 'Curl con agarre prono que enfatiza braquiorradial y antebrazo, mejorando el grosor del brazo.', 'Agarre prono al ancho de hombros, codos fijos; subí la barra sin rotar y bajá controlado.', 'Balancear el torso; mover los codos; agarrar demasiado ancho.', 'Usá cargas menores que en el curl supino por la palanca.', 'Subí 1-2 kg al completar 3x12.', 'Curl inverso con mancuernas.', array['Curl inverso con barra Z', 'Curl inverso con pausa'], array['Curl de muñeca con barra', 'Curl martillo']),

('Curl Zottman', 'Zottman curl', 'zottman curl, curl con rotación', 'Accesorios Calistenia', 'Antebrazos', 'Braquial y braquiorradial', 'Accesorios Calistenia', 'Intermedio', 2, 'Mancuernas', 'Mancuernas', 'Aislado', 'Flexión de codo', array['Bíceps braquial', 'Braquiorradial'], array['Braquial', 'Extensores de muñeca'], array['Core'], true, 'Abierta', 'Hipertrofia', 3, '10-12', 60, 1, 'Curl que combina subida supina y bajada prono, estimulando bíceps y antebrazo en una sola serie.', 'Subí las mancuernas en supinación, rotá a prono arriba y bajá lento con el pulgar arriba.', 'Rotar de golpe; soltar la tensión abajo; usar impulso.', 'Controlá la rotación para no forzar el codo.', 'Subí 1 kg al completar 3x12 con control.', 'Curl alterno con rotación.', array['Zottman con pausa', 'Zottman sentado'], array['Curl con mancuernas', 'Curl inverso con barra']),

('Pronosupinación con mancuerna', 'Dumbbell pronation-supination', 'pronosupinación, rotaciones de muñeca', 'Accesorios Calistenia', 'Antebrazos', 'Pronadores y supinadores', 'Accesorios Calistenia', 'Principiante', 1, 'Mancuerna y banco', 'Mancuernas', 'Aislado', 'Rotación', array['Pronador redondo', 'Supinador'], array['Bíceps braquial', 'Braquiorradial'], array['Core'], true, 'Abierta', 'Control corporal', 3, '15-20', 45, 1, 'Trabajo rotacional que refuerza pronadores y supinadores, protectores del codo en tirones.', 'Codo apoyado en el muslo con la mancuerna horizontal; rotá lentamente de prono a supino y volvé.', 'Mover el codo; rotar rápido; usar cargas altas.', 'Carga liviana; sensación de fatiga, no de dolor.', 'Subí 0,5 kg al completar 3x20 por lado.', 'Pronosupinación con barra sin peso (palo).', array['Pronosupinación con martillo de mano', 'Pronosupinación con barra'], array['Curl Zottman', 'Curl de muñeca con mancuernas']),

('Curl de dedos con barra', 'Barbell finger curl', 'curl de dedos, flexión de dedos', 'Accesorios Calistenia', 'Antebrazos', 'Flexores de los dedos', 'Accesorios Calistenia', 'Intermedio', 2, 'Banco, barra y discos', 'Barra', 'Aislado', 'Trabajo de agarre', array['Flexores de los dedos'], array['Flexores de muñeca'], array['Core'], false, 'Abierta', 'Fuerza', 3, '15-20', 45, 1, 'Fortalece los flexores de los dedos, base de un agarre sólido para colgados y barra fija.', 'Antebrazos apoyados, barra colgada de la primera falange; cerrá los dedos para subirla y abrí lento.', 'Usar la muñeca en lugar de los dedos; soltar de golpe; cargar demasiado.', 'Progresá muy lento; los tendones de los dedos toleran poca carga inicial.', 'Sumá 1 kg al dominar 3x20.', 'Curl de dedos con barra liviana o toalla.', array['Curl de dedos con pausa', 'Colgado con toalla'], array['Colgado en barra a dos manos', 'Curl de muñeca con barra']),

('Rodillo de muñeca', 'Wrist roller', 'rodillo de antebrazo, wrist roller', 'Accesorios Calistenia', 'Antebrazos', 'Flexores y extensores', 'Accesorios Calistenia', 'Intermedio', 2, 'Rodillo de muñeca con disco', 'Mixto', 'Aislado', 'Trabajo de agarre', array['Flexores de muñeca', 'Extensores de muñeca'], array['Flexores de los dedos'], array['Core', 'Deltoides anterior'], false, 'Abierta', 'Resistencia', 3, '2 subidas y bajadas', 60, 1, 'Trabajo continuo de antebrazo en ambos sentidos, ideal para resistencia de agarre.', 'Con brazos extendidos al frente, enrollá el peso subiendo y bajando en rollos controlados.', 'Flexionar los codos; balancear el torso; dejar caer el peso.', 'Usá brazos casi extendidos y peso moderado.', 'Sumá 1-2 kg o una serie al completar 3 series completas.', 'Rodillo con menos peso o menos recorrido.', array['Rodillo solo hacia arriba', 'Rodillo con brazos elevados'], array['Curl de muñeca con barra', 'Colgado en barra a dos manos']),

('Colgado en barra a dos manos', 'Two-arm dead hang', 'colgado pasivo, dead hang', 'Accesorios Calistenia', 'Agarre', 'Agarre de barra', 'Accesorios Calistenia', 'Principiante', 1, 'Barra fija', 'Peso corporal', 'Estabilidad', 'Trabajo de agarre', array['Flexores de los dedos', 'Flexores de muñeca'], array['Dorsal ancho', 'Trapecio'], array['Core', 'Manguito rotador'], false, 'Cerrada', 'Fuerza', 4, '30-60 s', 90, 0, 'Base del agarre calisténico: fortalece manos, dedos y la descompresión del hombro.', 'Colgate con agarre completo, hombros activos, cuerpo largo y piernas juntas sin balanceo.', 'Colgar con hombros totalmente pasivos y sin control; balancearse; soltar sin bajar.', 'Bajá con control para no impactar la barra; cuidá los callos.', 'Sumá segundos hasta 3x60 s y recién ahí pasá a lastre o una mano.', 'Colgado con los pies apoyados parcialmente.', array['Colgado activo (retracción)', 'Colgado con lastre'], array['Colgado en anillas', 'Colgado con toalla en barra']),

('Colgado a una mano', 'One-arm dead hang', 'colgado a una mano', 'Accesorios Calistenia', 'Agarre', 'Agarre unilateral', 'Accesorios Calistenia', 'Avanzado', 4, 'Barra fija', 'Peso corporal', 'Estabilidad', 'Trabajo de agarre', array['Flexores de los dedos'], array['Dorsal ancho', 'Trapecio', 'Antebrazo'], array['Core', 'Manguito rotador'], true, 'Cerrada', 'Fuerza', 3, '10-30 s por mano', 120, 0, 'Agarre unilateral exigente, transferencia directa a dominadas a una mano y one arm hang skills.', 'Sujetá la barra con una mano, hombro activo y cuerpo relajado pero alineado; evitá rotar el torso.', 'Dejar caer el hombro; girar el cuerpo; agarrar sin pulgar por comodidad.', 'Construí con colgado a dos manos antes; cuidá el codo y el hombro.', 'Sumá segundos por lado hasta 3x20 s.', 'Colgado a una mano con asistencia de la otra en la muñeca.', array['Una mano con lastre', 'Una mano con toalla'], array['Colgado en barra a dos manos', 'Colgado con toalla en barra']),

('Colgado con toalla en barra', 'Towel hang', 'colgado en toalla, towel hang', 'Accesorios Calistenia', 'Agarre', 'Agarre de pinza', 'Accesorios Calistenia', 'Intermedio', 2, 'Barra fija y toalla', 'Peso corporal', 'Estabilidad', 'Trabajo de agarre', array['Flexores de los dedos'], array['Flexores de muñeca', 'Dorsal ancho'], array['Core'], false, 'Cerrada', 'Fuerza', 3, '20-40 s', 90, 0, 'Colgado sobre toalla que aumenta el grosor y exige la pinza de dedos, muy útil para ski y front lever.', 'Pasá la toalla sobre la barra, agarrá los extremos y colgate manteniendo los hombros activos.', 'Agarrar la barra y no la toalla; balancearse; perder la pinza por fatiga.', 'Verificá que la toalla esté bien fijada antes de colgarte.', 'Sumá segundos o grosor de toalla al completar 3x30 s.', 'Colgado normal en barra.', array['Una toalla por mano', 'Toalla doble'], array['Colgado en barra a dos manos', 'Pinza de discos']),

('Colgado en anillas', 'Ring hang', 'colgado en anillas', 'Accesorios Calistenia', 'Agarre', 'Agarre de anillas', 'Accesorios Calistenia', 'Intermedio', 2, 'Anillas', 'Peso corporal', 'Estabilidad', 'Trabajo de agarre', array['Flexores de los dedos'], array['Dorsal ancho', 'Pectoral mayor'], array['Manguito rotador', 'Core'], false, 'Cerrada', 'Control corporal', 3, '30-60 s', 90, 0, 'Colgado en anillas que suma inestabilidad y activación del manguito, base del trabajo en anillas.', 'Tomá las anillas con agarre completo, activá los hombros y mantené las anillas quietas.', 'Dejar que las anillas giren; hombros pasivos; balanceo del cuerpo.', 'Asegurá las anillas y revisá las correas antes de usarlas.', 'Sumá tiempo hasta 3x60 s; luego pasá a support hold.', 'Colgado en barra fija.', array['Colgado en anillas con giro controlado', 'Support hold en anillas'], array['Colgado en barra a dos manos', 'Colgado con toalla en barra']),

('Pinza de discos', 'Plate pinch hold', 'pinza de discos, plate pinch', 'Accesorios Calistenia', 'Agarre', 'Agarre de pinza', 'Accesorios Calistenia', 'Intermedio', 2, 'Discos', 'Barra', 'Estabilidad', 'Trabajo de agarre', array['Flexores de los dedos', 'Flexor del pulgar'], array['Flexores de muñeca'], array['Core'], true, 'Cerrada', 'Fuerza', 3, '15-40 s por mano', 90, 0, 'Sostén de discos con los dedos que desarrolla la pinza y el pulgar, gran transferencia al agarre de barra gruesa.', 'Pellizcá el canto de uno o dos discos entre el pulgar y los dedos y sostené con el brazo al costado.', 'Apoyar el disco en la palma; usar dos manos; sostener con los dedos estirados.', 'Empezá con discos livianos; el pulgar es propenso a molestias.', 'Sumá segundos o disco más pesado al completar 3x30 s.', 'Pinza con disco único liviano o toalla.', array['Pinza con dos discos', 'Pinza con mancuerna por la cabeza'], array['Colgado con toalla en barra', 'Sostén isométrico de mancuernas']),

('Sostén isométrico de mancuernas', 'Dumbbell static hold', 'grip hold, sostén de mancuernas', 'Accesorios Calistenia', 'Agarre', 'Agarre de barra', 'Accesorios Calistenia', 'Principiante', 1, 'Mancuernas pesadas', 'Mancuernas', 'Estabilidad', 'Trabajo de agarre', array['Flexores de los dedos', 'Flexores de muñeca'], array['Trapecio', 'Antebrazo'], array['Core', 'Glúteos'], true, 'Cerrada', 'Fuerza', 3, '30-45 s por mano', 90, 0, 'Sostén estático que permite cargar el agarre de forma progresiva sin exigir a los hombros.', 'Tomá mancuernas pesadas y quedate de pie con brazos al costado, hombros atrás y core firme.', 'Encoger los hombros; inclinar el torso; apoyar las mancuernas en el muslo.', 'Mantené la espalda neutra y bajá las mancuernas con control.', 'Sumá segundos o peso al completar 3x45 s por mano.', 'Sostén con mancuernas más livianas.', array['Sostén caminando (acarreo)', 'Sostén con pausa al fallo'], array['Paseo del granjero con mancuernas', 'Pinza de discos']),

('Elevación de piernas colgado en barra', 'Hanging leg raise', 'elevación de piernas colgado, hanging leg raise', 'Accesorios Calistenia', 'Core', 'Recto abdominal (porción inferior)', 'Accesorios Calistenia', 'Intermedio', 3, 'Barra fija', 'Peso corporal', 'Compuesto', 'Flexión de tronco', array['Recto abdominal', 'Flexores de cadera'], array['Oblicuos'], array['Dorsal ancho', 'Agarre'], false, 'Cerrada', 'Control corporal', 3, '8-12', 90, 1, 'Core colgado de alto valor: desarrolla flexión de tronco y control lumbo-pélvico para front lever y L-sit.', 'Colgado de la barra, retraé ligeramente y subí las piernas juntas y extendidas hasta la horizontal o más.', 'Balancearse; usar impulso de cadera; dejar caer las piernas.', 'Bajá controlado para proteger la espalda baja.', 'Pasá a toes to bar o sumá lastre al completar 3x12.', 'Elevación de rodillas colgado en barra.', array['Elevación de piernas a la barra', 'Elevación de piernas con lastre'], array['Elevación de rodillas colgado en barra', 'Toes to bar']),

('Elevación de rodillas colgado en barra', 'Hanging knee raise', 'elevación de rodillas colgado', 'Accesorios Calistenia', 'Core', 'Recto abdominal (porción inferior)', 'Accesorios Calistenia', 'Principiante', 2, 'Barra fija', 'Peso corporal', 'Compuesto', 'Flexión de tronco', array['Recto abdominal', 'Flexores de cadera'], array['Oblicuos'], array['Dorsal ancho', 'Agarre'], false, 'Cerrada', 'Control corporal', 3, '10-15', 75, 1, 'Regresión directa de la elevación de piernas que enseña a curvar la pelvis sin balanceo.', 'Colgado, subí las rodillas al pecho redondeando la zona lumbar y bajá lento sin balancearte.', 'Solo subir las rodillas sin curvar la pelvis; balanceo; soltar de golpe.', 'Priorizá el control sobre el rango; ideal como entrada al trabajo colgado.', 'Pasá a piernas estiradas al completar 3x15 limpias.', 'Elevación de rodillas en paralelas.', array['Elevación de rodillas a un lado', 'Elevación de rodillas con pausa'], array['Elevación de piernas colgado en barra', 'Elevación de piernas tumbado con disco']),

('Toes to bar', 'Toes to bar', 'pies a la barra, T2B', 'Accesorios Calistenia', 'Core', 'Recto abdominal (porción inferior)', 'Accesorios Calistenia', 'Avanzado', 4, 'Barra fija', 'Peso corporal', 'Compuesto', 'Flexión de tronco', array['Recto abdominal', 'Flexores de cadera'], array['Oblicuos', 'Dorsal ancho'], array['Agarre', 'Core'], false, 'Cerrada', 'Control corporal', 3, '6-10', 90, 1, 'Flexión de tronco completa colgado, transferencia directa a remos, front lever y gimnásticos.', 'Desde colgado, subí las piernas extendidas hasta tocar la barra con los pies y bajá con control.', 'Balanceo tipo kip; doblar demasiado las rodillas; bajar sin freno.', 'Construí con elevación de piernas; evitá el arqueo lumbar al bajar.', 'Sumá reps o lastre al completar 3x10 estrictas.', 'Elevación de piernas colgado en barra.', array['Toes to bar con pausa', 'Toes to bar lentos'], array['Elevación de piernas colgado en barra', 'Dragon flag']),

('Hollow hold', 'Hollow body hold', 'plancha hueca, hollow body', 'Accesorios Calistenia', 'Core', 'Anti-extensión', 'Accesorios Calistenia', 'Principiante', 1, 'Suelo', 'Peso corporal', 'Estabilidad', 'Anti-extensión', array['Recto abdominal', 'Transverso abdominal'], array['Flexores de cadera', 'Oblicuos'], array['Cuádriceps', 'Dorsal ancho'], false, 'Cerrada', 'Control corporal', 4, '20-45 s', 60, 0, 'Posición fundamental del control corporal que enseña a mantener la pelvis retrovertida y el tronco rígido.', 'Acostado, pegá la lumbar al suelo, elevá piernas y hombros y sostené con brazos extendidos.', 'Arquear la lumbar; aguantar la respiración; bajar las piernas demasiado.', 'Si aparece dolor lumbar, elevá más las piernas o doblá las rodillas.', 'Sumá segundos hasta 3x45 s antes de lastrar.', 'Hollow hold con rodillas dobladas.', array['Hollow hold con lastre', 'Hollow hold con brazos sobre la cabeza'], array['Plancha frontal lastrada', 'Hollow rocks lastrado']),

('Hollow rocks lastrado', 'Weighted hollow rocks', 'hollow rocks, balanceo hueco', 'Accesorios Calistenia', 'Core', 'Anti-extensión', 'Accesorios Calistenia', 'Intermedio', 2, 'Lastre (disco o chaleco)', 'Peso corporal', 'Compuesto', 'Anti-extensión', array['Recto abdominal'], array['Flexores de cadera', 'Oblicuos'], array['Dorsal ancho', 'Cuádriceps'], false, 'Cerrada', 'Control corporal', 3, '12-20', 60, 1, 'Versión dinámica del hollow que suma carga y exige control anti-extensión durante el balanceo.', 'Mantené la posición hueca y balanceate sobre la espalda sin dejar que la lumbar se arquee.', 'Arquear la lumbar; perder la forma; balancearse con las piernas.', 'Dominá el hollow hold antes de lastrar.', 'Sumá reps o peso manteniendo 3x15 con forma perfecta.', 'Hollow rocks a peso corporal.', array['Hollow rocks con pausa arriba', 'Hollow rocks con disco'], array['Hollow hold', 'Plancha frontal lastrada']),

('Plancha frontal lastrada', 'Weighted front plank', 'plancha con peso, plank lastrada', 'Accesorios Calistenia', 'Core', 'Anti-extensión', 'Accesorios Calistenia', 'Principiante', 2, 'Lastre (disco o chaleco)', 'Peso corporal', 'Estabilidad', 'Anti-extensión', array['Recto abdominal', 'Transverso abdominal'], array['Glúteos', 'Cuádriceps'], array['Oblicuos', 'Dorsal ancho'], false, 'Cerrada', 'Control corporal', 3, '30-60 s', 60, 0, 'Plancha con carga que refuerza la anti-extensión y transfiere a planche y front lever.', 'Apoyá antebrazos y puntas de pie, cuerpo en línea, glúteos activos y lumbar neutra; sostené.', 'Bajar la cadera; subir los glúteos; cargar la lumbar.', 'Retirá el lastre con ayuda para no golpearte.', 'Sumá segundos o peso al completar 3x60 s.', 'Plancha frontal a peso corporal.', array['Plancha frontal con elevación de un pie', 'Plancha frontal con toque de hombro'], array['Hollow hold', 'Plancha Copenhagen']),

('Dragon flag', 'Dragon flag', 'bandera de dragón, dragon flag', 'Accesorios Calistenia', 'Core', 'Anti-extensión', 'Accesorios Calistenia', 'Avanzado', 4, 'Banco, barra o anillas', 'Peso corporal', 'Compuesto', 'Anti-extensión', array['Recto abdominal', 'Transverso abdominal'], array['Dorsal ancho', 'Glúteos'], array['Oblicuos', 'Agarre'], false, 'Cerrada', 'Control corporal', 3, '5-10', 120, 1, 'Reto avanzado de control corporal que exige un tronco rígido y coordinación total del core.', 'Sujetá un punto fijo detrás de la cabeza, elevá el cuerpo recto desde los hombros y bajá sin arquear.', 'Doblar la cadera; tocar el suelo con la espalda; perder el control.', 'Empezá con tuck y avanzá por fases; nunca lo hagas fatigado.', 'Pasá de tuck a una pierna y luego a completo.', 'Dragon flag tuck o con una pierna.', array['Dragon flag tuck', 'Dragon flag a una pierna'], array['Toes to bar', 'Hollow rocks lastrado']),

('Sit up con disco', 'Weighted sit-up', 'abdominal lastrado, sit up con peso', 'Accesorios Calistenia', 'Core', 'Recto abdominal (flexión de tronco)', 'Accesorios Calistenia', 'Intermedio', 2, 'Suelo y disco', 'Mixto', 'Aislado', 'Flexión de tronco', array['Recto abdominal'], array['Flexores de cadera', 'Oblicuos'], array['Transverso abdominal'], false, 'Cerrada', 'Hipertrofia', 3, '12-15', 60, 1, 'Flexión de tronco cargada, útil para hipertrofia del recto abdominal con progresión de peso.', 'Con disco al pecho, subí redondeando la columna hasta sentarte y bajá controlando.', 'Usar impulso de cadera; tirar del cuello; bajar sin control.', 'Evitá cargas altas si hay molestia lumbar; mantené el disco pegado.', 'Sumá 2,5 kg al completar 3x15 controladas.', 'Sit up a peso corporal o crunch.', array['Sit up con disco sobre la cabeza', 'Sit up en banco declinado'], array['Crunch con disco', 'Elevación de piernas tumbado con disco']),

('Elevación de piernas tumbado con disco', 'Weighted lying leg raise', 'elevación de piernas lastrada', 'Accesorios Calistenia', 'Core', 'Recto abdominal (porción inferior)', 'Accesorios Calistenia', 'Intermedio', 2, 'Suelo y disco', 'Mixto', 'Aislado', 'Flexión de tronco', array['Recto abdominal', 'Flexores de cadera'], array['Oblicuos'], array['Transverso abdominal'], false, 'Cerrada', 'Hipertrofia', 3, '12-15', 60, 1, 'Flexión de tronco con carga que enfatiza la porción inferior del abdomen.', 'Acostado con disco entre los pies, subí las piernas rectas hasta la vertical y bajá sin tocar el suelo.', 'Arquear la lumbar; dejar caer las piernas; usar impulso.', 'Mantené la lumbar apoyada; si no, doblá las rodillas.', 'Sumá 1-2 kg o reps al completar 3x15.', 'Elevación de piernas tumbado a peso corporal.', array['Elevación de piernas con pausa abajo', 'Elevación de piernas con disco sobre la cabeza'], array['Elevación de rodillas colgado en barra', 'Crunch con disco']),

('Crunch con disco', 'Weighted crunch', 'crunch lastrado, abdominal con disco', 'Accesorios Calistenia', 'Core', 'Recto abdominal (flexión de tronco)', 'Accesorios Calistenia', 'Principiante', 1, 'Suelo o banco y disco', 'Mixto', 'Aislado', 'Flexión de tronco', array['Recto abdominal'], array['Oblicuos'], array['Transverso abdominal'], false, 'Cerrada', 'Hipertrofia', 3, '15-20', 45, 1, 'Flexión de tronco de corto recorrido con carga, fácil de progresar y de gran bombeo abdominal.', 'Con disco al pecho, redondeá la columna llevando las costillas a la pelvis y bajá lento.', 'Tirar del cuello; usar la cadera; recorrido mínimo.', 'Cuidá la zona cervical manteniendo la barbilla lejos del pecho.', 'Sumá 2,5 kg al completar 3x20.', 'Crunch a peso corporal.', array['Crunch con disco sobre la cabeza', 'Crunch en polea (si hay polea)'], array['Sit up con disco', 'Elevación de piernas tumbado con disco']),

('Russian twist con disco', 'Weighted Russian twist', 'giro ruso, rotación con disco', 'Accesorios Calistenia', 'Core', 'Oblicuos (rotación)', 'Accesorios Calistenia', 'Intermedio', 2, 'Suelo y disco', 'Mixto', 'Aislado', 'Rotación', array['Oblicuos'], array['Recto abdominal'], array['Transverso abdominal', 'Flexores de cadera'], false, 'Cerrada', 'Hipertrofia', 3, '12-15 por lado', 45, 1, 'Rotación cargada del tronco que refuerza los oblicuos y la estabilidad rotacional.', 'Sentado con torso inclinado atrás, llevá el disco de un lado al otro girando el tronco, no solo los brazos.', 'Rotar solo los brazos; encorvar la espalda; usar impulso.', 'Si molesta la lumbar, mantené el torso más alto o sin peso.', 'Sumá 1,5-2,5 kg al completar 3x15 por lado.', 'Russian twist a peso corporal.', array['Russian twist con pies levantados', 'Russian twist con disco sobre la cabeza'], array['Rotación de tronco con landmine', 'Crunch con disco']),

('Rotación de tronco con landmine', 'Landmine rotation', 'giro con barra en esquina, landmine twist', 'Accesorios Calistenia', 'Core', 'Anti-rotación', 'Accesorios Calistenia', 'Intermedio', 2, 'Barra en esquina con disco', 'Barra', 'Compuesto', 'Anti-rotación', array['Oblicuos'], array['Recto abdominal', 'Dorsal ancho'], array['Glúteos', 'Core'], false, 'Cerrada', 'Control corporal', 3, '10-12 por lado', 60, 1, 'Rotación guiada con barra que permite cargar el gesto sin perder el control lumbo-pélvico.', 'De pie con la barra tomada a dos manos frente al cuerpo, girá el tronco llevando la barra de un lado al otro con control.', 'Rotar solo los brazos; mover los pies; perder la posición del core.', 'Mantené la cadera estable y frená el retorno de la barra.', 'Sumá disco o reps al completar 3x12 por lado.', 'Rotación con barra sin disco (palo).', array['Landmine a rodillas', 'Landmine con pausa en el centro'], array['Russian twist con disco', 'Plancha Copenhagen']),

('Sentadilla con barra', 'Barbell back squat', 'sentadilla trasera, back squat', 'Accesorios Calistenia', 'Piernas', 'Cuádriceps + glúteo', 'Accesorios Calistenia', 'Intermedio', 3, 'Rack, barra y discos', 'Barra', 'Compuesto', 'Dominante de rodilla', array['Cuádriceps', 'Glúteo mayor'], array['Isquiotibiales', 'Aductores', 'Erectores espinales'], array['Core', 'Pantorrillas'], false, 'Cerrada', 'Fuerza', 4, '5-8', 150, 2, 'Patrón dominante de rodilla por excelencia; construye fuerza y masa de piernas que sostiene saltos y skills.', 'Barra en trapecios, pies al ancho de hombros, bajá con cadera atrás y rodillas hacia afuera hasta romper paralelo y subí empujando el suelo.', 'Levantar los talones; rodillas hacia adentro; perder la curva lumbar; mirar arriba.', 'Usá rack con seguros; no fuerces profundidad si hay molestia de rodilla o cadera.', 'Subí 2,5-5 kg al completar 4x8 con RIR 2 y técnica estable.', 'Sentadilla goblet o sentadilla con peso corporal.', array['Sentadilla con pausa', 'Sentadilla tempo lento', 'Sentadilla búlgara con mancuernas'], array['Sentadilla frontal con barra', 'Prensa de piernas (si hay máquina)']),

('Sentadilla frontal con barra', 'Front squat', 'frontal, front squat', 'Accesorios Calistenia', 'Piernas', 'Cuádriceps', 'Accesorios Calistenia', 'Avanzado', 3, 'Rack, barra y discos', 'Barra', 'Compuesto', 'Dominante de rodilla', array['Cuádriceps'], array['Glúteo mayor', 'Erectores espinales'], array['Core', 'Pantorrillas'], false, 'Cerrada', 'Fuerza', 4, '5-8', 150, 2, 'Variante frontal que enfatiza cuádriceps y exige un torso muy erguido, muy útil para la postura en skills.', 'Barra en hombros con codos altos, bajá manteniendo el torso vertical y subí sin perder los codos arriba.', 'Bajar los codos y perder la barra; inclinarse adelante; talones levantados.', 'Empezá liviano para aprender la posición; usá seguros.', 'Subí 2,5 kg al completar 4x6 sin perder el torso.', 'Sentadilla goblet o sentadilla con barra.', array['Front squat con pausa', 'Front squat con tempo'], array['Sentadilla con barra', 'Sentadilla búlgara con mancuernas']),

('Sentadilla búlgara con mancuernas', 'Bulgarian split squat', 'búlgara, split squat búlgaro', 'Accesorios Calistenia', 'Piernas', 'Cuádriceps + glúteo (unilateral)', 'Accesorios Calistenia', 'Intermedio', 2, 'Banco y mancuernas', 'Mancuernas', 'Compuesto', 'Dominante de rodilla', array['Cuádriceps', 'Glúteo mayor'], array['Isquiotibiales', 'Aductores'], array['Core', 'Glúteo medio'], true, 'Cerrada', 'Hipertrofia', 3, '8-12 por pierna', 90, 2, 'Unilateral muy eficiente para cuádriceps, glúteo y equilibrio; corrige asimetrías entre piernas.', 'Pie trasero en banco, bajá controlando hasta que la rodilla delantera llegue cerca del suelo y empujá con el talón.', 'Ponerse demasiado lejos o cerca del banco; rodilla hacia adentro; perder el equilibrio.', 'Asegurá el pie trasero; empezá sin peso si falta equilibrio.', 'Subí 1-2 kg por mancuerna al completar 3x10 por pierna.', 'Zancada estática con apoyo.', array['Búlgara con barra', 'Búlgara con pausa abajo'], array['Zancada caminando con mancuernas', 'Pistol squat con lastre']),

('Zancada caminando con mancuernas', 'Dumbbell walking lunge', 'zancadas caminando, walking lunge', 'Accesorios Calistenia', 'Piernas', 'Cuádriceps + glúteo (unilateral)', 'Accesorios Calistenia', 'Intermedio', 2, 'Mancuernas', 'Mancuernas', 'Compuesto', 'Dominante de rodilla', array['Cuádriceps', 'Glúteo mayor'], array['Isquiotibiales', 'Aductores'], array['Core', 'Pantorrillas'], true, 'Cerrada', 'Hipertrofia', 3, '10-12 por pierna', 90, 2, 'Patrón unilateral funcional que suma trabajo de estabilidad y potencia en cada zancada.', 'Con mancuernas al costado, dá un paso largo, bajá la rodilla de atrás cerca del suelo y avanzá alternando.', 'Pasos cortos; rodilla hacia adentro; torso muy inclinado.', 'Hacelo en un espacio libre; cuidá el equilibrio al inicio.', 'Subí carga o pasos al completar 3x12 por pierna.', 'Zancada estática sin peso.', array['Zancada hacia atrás', 'Zancada con pausa'], array['Sentadilla búlgara con mancuernas', 'Peso muerto a una pierna con mancuerna']),

('Sentadilla goblet con mancuerna', 'Goblet squat', 'sentadilla goblet, sentadilla con mancuerna al pecho', 'Accesorios Calistenia', 'Piernas', 'Cuádriceps + glúteo', 'Accesorios Calistenia', 'Principiante', 1, 'Mancuerna', 'Mancuernas', 'Compuesto', 'Dominante de rodilla', array['Cuádriceps', 'Glúteo mayor'], array['Aductores', 'Isquiotibiales'], array['Core', 'Erectores espinales'], false, 'Cerrada', 'Hipertrofia', 3, '10-15', 75, 2, 'Sentadilla con carga al pecho ideal para aprender el patrón y ganar fuerza con poco material.', 'Sujetá la mancuerna al pecho, bajá sentándote entre los talones con torso erguido y subí empujando el suelo.', 'Inclinarse adelante; levantar talones; perder la curva neutra.', 'Mantené la mancuerna pegada al pecho; excelente opción como calentamiento con carga.', 'Sumá 2-4 kg al completar 3x15.', 'Sentadilla con peso corporal.', array['Goblet con pausa', 'Goblet tempo lento'], array['Sentadilla con barra', 'Sentadilla frontal con barra']),

('Peso muerto con barra', 'Barbell deadlift', 'peso muerto convencional, deadlift', 'Accesorios Calistenia', 'Piernas', 'Cadena posterior', 'Accesorios Calistenia', 'Avanzado', 3, 'Barra y discos', 'Barra', 'Compuesto', 'Bisagra de cadera', array['Glúteo mayor', 'Isquiotibiales', 'Erectores espinales'], array['Dorsal ancho', 'Trapecio', 'Cuádriceps'], array['Core', 'Agarre'], false, 'Cerrada', 'Fuerza', 4, '3-6', 180, 2, 'Patrón de bisagra con barra que construye la cadena posterior y un agarre de hierro.', 'Barra sobre medio pie, bisagra de cadera con espalda neutra, empujá el suelo y levantá juntando cadera y rodillas.', 'Redondear la espalda; tirar con los brazos; alejar la barra del cuerpo.', 'Priorizá la técnica; no uses cargas máximas sin supervisión.', 'Subí 5 kg al completar 4x5 con técnica impecable.', 'Peso muerto rumano con barra o con mancuernas.', array['Peso muerto desde bloque', 'Peso muerto a una pierna con mancuerna'], array['Peso muerto rumano con barra', 'Hip thrust con barra']),

('Peso muerto rumano con barra', 'Romanian deadlift', 'RDL, peso muerto rumano', 'Accesorios Calistenia', 'Piernas', 'Isquiotibiales', 'Accesorios Calistenia', 'Intermedio', 2, 'Barra y discos', 'Barra', 'Compuesto', 'Bisagra de cadera', array['Isquiotibiales', 'Glúteo mayor'], array['Erectores espinales', 'Dorsal ancho'], array['Core', 'Agarre'], false, 'Cerrada', 'Hipertrofia', 3, '8-10', 120, 2, 'Bisagra de cadera con énfasis en isquiotibiales y glúteo, clave para saltos y estabilidad de rodilla.', 'De pie con barra, rodillas casi extendidas, bajá la barra por las piernas llevando la cadera atrás hasta sentir el estiramiento y subí apretando glúteos.', 'Doblar demasiado las rodillas; redondear la espalda; alejar la barra.', 'Bajá hasta donde mantengas la espalda neutra, sin buscar el suelo.', 'Subí 2,5-5 kg al completar 3x10 con control.', 'Peso muerto a una pierna con mancuerna o con barra liviana.', array['RDL con pausa abajo', 'RDL con barra a una pierna'], array['Peso muerto con barra', 'Curl nórdico']),

('Peso muerto a una pierna con mancuerna', 'Single-leg Romanian deadlift', 'peso muerto a una pierna, single leg RDL', 'Accesorios Calistenia', 'Piernas', 'Isquiotibiales (unilateral)', 'Accesorios Calistenia', 'Intermedio', 2, 'Mancuerna', 'Mancuernas', 'Compuesto', 'Bisagra de cadera', array['Isquiotibiales', 'Glúteo mayor'], array['Erectores espinales', 'Glúteo medio'], array['Core', 'Agarre'], true, 'Cerrada', 'Control corporal', 3, '8-10 por pierna', 90, 2, 'Bisagra unilateral que suma control de cadera y equilibrio, muy útil para el sostén a una pierna.', 'Con mancuerna en una mano, apoyá el peso en un pie, llevá la cadera atrás mientras la otra pierna se extiende atrás y volvé apretando el glúteo.', 'Rotar la cadera; redondear la espalda; perder el equilibrio.', 'Empezá sin peso y cerca de una pared para apoyarte.', 'Subí 1-2 kg al completar 3x10 por pierna.', 'Bisagra a dos piernas o a una sin peso.', array['Single leg RDL con barra', 'Single leg RDL con pausa'], array['Peso muerto rumano con barra', 'Puente de glúteo a una pierna']),

('Hip thrust con barra', 'Barbell hip thrust', 'empuje de cadera, hip thrust', 'Accesorios Calistenia', 'Piernas', 'Glúteo mayor', 'Accesorios Calistenia', 'Intermedio', 2, 'Banco, barra y discos o mancuerna', 'Barra', 'Compuesto', 'Extensión de cadera', array['Glúteo mayor'], array['Isquiotibiales', 'Cuádriceps'], array['Core', 'Aductores'], false, 'Cerrada', 'Hipertrofia', 3, '8-12', 120, 2, 'Extensión de cadera con máxima activación de glúteo, base de la potencia de salto y sprint.', 'Espalda alta en banco y barra sobre la cadera, subí hasta alinear cadera con hombros y rodillas y apretá arriba.', 'Hiperextender la lumbar; empujar con los pies lejos; no bloquear arriba.', 'Usá almohadilla en la barra; mantené las costillas abajo.', 'Subí 5 kg al completar 3x12 con pausa arriba.', 'Puente de glúteo a una pierna.', array['Hip thrust a una pierna', 'Hip thrust con pausa'], array['Puente de glúteo a una pierna', 'Peso muerto rumano con barra']),

('Puente de glúteo a una pierna', 'Single-leg glute bridge', 'puente a una pierna, glute bridge', 'Accesorios Calistenia', 'Piernas', 'Glúteo mayor (unilateral)', 'Accesorios Calistenia', 'Principiante', 1, 'Suelo', 'Peso corporal', 'Aislado', 'Extensión de cadera', array['Glúteo mayor'], array['Isquiotibiales', 'Glúteo medio'], array['Core'], true, 'Cerrada', 'Hipertrofia', 3, '12-15 por pierna', 60, 1, 'Extensión de cadera sin material que activa el glúteo y corrige asimetrías.', 'Acostado con una rodilla flexionada y la otra pierna extendida, subí la cadera apretando el glúteo y bajá controlando.', 'Arquear la lumbar; empujar con el talón lejos; subir con la otra pierna.', 'Mantené las costillas abajo y el core activo.', 'Sumá reps o elevá el pie en un banco.', 'Puente de glúteo a dos piernas.', array['Puente a una pierna con pausa', 'Puente a una pierna sobre banco'], array['Hip thrust con barra', 'Peso muerto a una pierna con mancuerna']),

('Curl nórdico', 'Nordic hamstring curl', 'nórdico, curl nórdico', 'Accesorios Calistenia', 'Piernas', 'Isquiotibiales (excéntrico)', 'Accesorios Calistenia', 'Avanzado', 4, 'Compañero o apoyo, almohadilla', 'Peso corporal', 'Compuesto', 'Flexión de rodilla', array['Isquiotibiales'], array['Glúteo mayor', 'Gastrocnemio'], array['Core'], false, 'Cerrada', 'Fuerza', 3, '4-8', 150, 2, 'El mejor ejercicio excéntrico para isquiotibiales; reduce el riesgo de lesión y mejora el sprint.', 'Arrodillado con los tobillos fijos, bajá el cuerpo lo más lento posible controlando con los isquios y frenate con las manos.', 'Doblar la cadera; caer sin control; no frenar con las manos.', 'Empezá con asistencia; el DOMS es intenso, dosificá el volumen.', 'Bajá con más control y menos ayuda al completar 3x6.', 'Curl nórdico asistido con banda o con compañero.', array['Nórdico excéntrico lento', 'Curl nórdico con pausa'], array['Peso muerto rumano con barra', 'Curl femoral con mancuerna']),

('Sentadilla sissy', 'Sissy squat', 'sissy squat', 'Accesorios Calistenia', 'Piernas', 'Cuádriceps (recto femoral)', 'Accesorios Calistenia', 'Avanzado', 3, 'Peso corporal (o mancuerna)', 'Peso corporal', 'Aislado', 'Dominante de rodilla', array['Cuádriceps'], array['Flexores de cadera'], array['Core'], false, 'Abierta', 'Hipertrofia', 3, '8-12', 90, 2, 'Aislamiento exigente de cuádriceps que estira el recto femoral y refuerza las rodillas.', 'De pie, subí a las puntas y llevá las rodillas adelante mientras inclinás el torso atrás, bajá y volvé extendiendo.', 'Bajar más de lo que controlás; perder las puntas; redondear el torso.', 'Cuidá las rodillas y los tendones; empezá con rango corto.', 'Sumá rango o reps al completar 3x12 sin molestia.', 'Sentadilla con talones elevados o extensión con peso corporal.', array['Sissy con lastre', 'Sissy con pausa abajo'], array['Sentadilla frontal con barra', 'Pistol squat con lastre']),

('Pistol squat con lastre', 'Weighted pistol squat', 'pistol, sentadilla a una pierna', 'Accesorios Calistenia', 'Piernas', 'Cuádriceps + glúteo (unilateral)', 'Accesorios Calistenia', 'Avanzado', 4, 'Lastre (disco o mancuerna) y apoyo opcional', 'Peso corporal', 'Compuesto', 'Dominante de rodilla', array['Cuádriceps', 'Glúteo mayor'], array['Isquiotibiales', 'Aductores'], array['Core', 'Glúteo medio'], true, 'Cerrada', 'Fuerza', 3, '5-8 por pierna', 120, 2, 'Sentadilla a una pierna que combina fuerza, movilidad y equilibrio con transferencia a skills.', 'De pie sobre un pie, extendé la otra pierna al frente y bajá controlando hasta abajo manteniendo el talón apoyado.', 'Levantar el talón; rodilla hacia adentro; perder el control por falta de movilidad.', 'Construí con asistencia y movilidad de tobillo; cuidá la rodilla.', 'Sumá lastre o reps al completar 3x6 por pierna.', 'Pistol asistida con anilla o cajón.', array['Pistol sobre cajón', 'Pistol con pausa abajo'], array['Sentadilla búlgara con mancuernas', 'Sentadilla sissy']),

('Elevación de talones de pie con mancuernas', 'Standing dumbbell calf raise', 'gemelos de pie, elevación de talones', 'Accesorios Calistenia', 'Piernas', 'Gastrocnemio', 'Accesorios Calistenia', 'Principiante', 1, 'Mancuernas y escalón', 'Mancuernas', 'Aislado', 'Flexión plantar', array['Gastrocnemio'], array['Sóleo'], array['Core', 'Tibial anterior'], false, 'Cerrada', 'Hipertrofia', 4, '12-20', 60, 1, 'Elevación de talones que desarrolla la pantorrilla y la potencia de salto y estiramiento.', 'De pie en un escalón con los talones al aire, subí lo máximo posible y bajá estirando el gemelo.', 'Rebotar; recorrido parcial; doblar las rodillas.', 'Controlá la bajada; el tendón de Aquiles tolera bien la carga si es progresiva.', 'Subí 2-4 kg al completar 4x20 con pausa arriba.', 'Elevación de talones a peso corporal.', array['Elevación de talones con pausa', 'Elevación de talones sentado'], array['Elevación de talones a una pierna con mancuerna', 'Gemelos en escalón']),

('Elevación de talones a una pierna con mancuerna', 'Single-leg dumbbell calf raise', 'gemelos a una pierna', 'Accesorios Calistenia', 'Piernas', 'Gastrocnemio y sóleo (unilateral)', 'Accesorios Calistenia', 'Intermedio', 2, 'Mancuerna y escalón o apoyo', 'Mancuernas', 'Aislado', 'Flexión plantar', array['Gastrocnemio', 'Sóleo'], array['Tibial anterior'], array['Core', 'Glúteo medio'], true, 'Cerrada', 'Hipertrofia', 3, '12-15 por pierna', 60, 1, 'Trabajo unilateral de pantorrilla que corrige asimetrías y suma rango completo.', 'Con una mancuerna, apoyate en una pierna en el escalón y subí el talón al máximo, bajá lento.', 'Usar la pierna de apoyo; rebotar; recorrido corto.', 'Sujetate de algo con la mano libre para estabilizar.', 'Subí 1-2 kg al completar 3x15 por pierna.', 'Elevación de talones a una pierna sin peso.', array['A una pierna con pausa arriba', 'A una pierna con isométrico'], array['Elevación de talones de pie con mancuernas', 'Gemelos en escalón']),

('Gemelos en escalón', 'Calf raise on step', 'gemelos en escalón, calf raise', 'Accesorios Calistenia', 'Piernas', 'Gastrocnemio y sóleo', 'Accesorios Calistenia', 'Principiante', 1, 'Escalón o cajón', 'Peso corporal', 'Aislado', 'Flexión plantar', array['Gastrocnemio', 'Sóleo'], array['Tibial anterior'], array['Core'], false, 'Cerrada', 'Resistencia', 3, '15-25', 45, 1, 'Elevación de talones con peso corporal que permite rango completo y alta repetición.', 'En el borde de un escalón, subí al máximo las puntas y bajá hasta estirar el talón por debajo del nivel.', 'Rebotar; no completar el rango; balancearse.', 'Cuidá el agarre de la barandilla para no caer.', 'Pasá a una pierna o sumá mancuernas al dominar 3x25.', 'Elevación de talones en el suelo.', array['Gemelos en escalón a una pierna', 'Gemelos en escalón con tempo'], array['Elevación de talones de pie con mancuernas', 'Elevación de talones a una pierna con mancuerna']),

('Dominadas escapulares', 'Scapular pull-up', 'dominadas escapulares, scapular pull', 'Accesorios Calistenia', 'Prehabilitación', 'Escápula y manguito rotador', 'Accesorios Calistenia', 'Principiante', 2, 'Barra fija', 'Peso corporal', 'Estabilidad', 'Elevación escapular', array['Trapecio inferior', 'Romboides'], array['Dorsal ancho', 'Pectoral menor'], array['Core', 'Manguito rotador'], false, 'Cerrada', 'Control corporal', 3, '8-12', 60, 1, 'Educativo de la escápula: enseña a deprimir y retraer antes de tirar, previniendo lesiones de hombro.', 'Colgado con brazos rectos, sin doblar codos bajá y juntá los omóplatos elevando apenas el cuerpo.', 'Doblar los codos; usar balanza; encoger los hombros.', 'Movimiento chico y controlado; calidad antes que cantidad.', 'Sumá reps y pausa de 1 s arriba al completar 3x12.', 'Colgado activo en barra.', array['Escapulares en anillas', 'Escapulares con pausa'], array['Retracción escapular en anillas', 'Colgado en barra a dos manos']),

('Retracción escapular en anillas', 'Ring scapular row', 'remo escapular en anillas, scapular row', 'Accesorios Calistenia', 'Prehabilitación', 'Escápula y manguito rotador', 'Accesorios Calistenia', 'Intermedio', 2, 'Anillas', 'Peso corporal', 'Estabilidad', 'Elevación escapular', array['Romboides', 'Trapecio medio'], array['Dorsal ancho', 'Deltoides posterior'], array['Manguito rotador', 'Core'], false, 'Cerrada', 'Control corporal', 3, '8-12', 60, 1, 'Trabajo de retracción pura que mejora la posición escapular en remos y dominadas.', 'De espaldas a las anillas, brazos rectos y cuerpo inclinado atrás, juntá los omóplatos sin doblar codos y volvé.', 'Doblar los codos; subir los hombros; perder el cuerpo en línea.', 'Ajustá la inclinación para dosificar la dificultad.', 'Incrementá la inclinación o sumá pausa al completar 3x12.', 'Escapulares colgado en barra.', array['Retracción en anillas con pausa', 'Retracción en anillas a una mano'], array['Dominadas escapulares', 'Remo invertido en anillas']),

('Flexión con protracción', 'Push-up plus', 'push up plus, flexión con serrato', 'Accesorios Calistenia', 'Prehabilitación', 'Serrato anterior y escápula', 'Accesorios Calistenia', 'Principiante', 1, 'Suelo o paralelas', 'Peso corporal', 'Estabilidad', 'Empuje horizontal', array['Serrato anterior'], array['Pectoral menor', 'Deltoides anterior'], array['Core', 'Romboides'], false, 'Cerrada', 'Control corporal', 3, '10-15', 60, 1, 'Activa el serrato anterior al final del empuje, fundamental para la salud del hombro y el apoyo en planche.', 'En posición de plancha alta o flexión, empujá el suelo alejando los omóplatos al final del recorrido y volvé.', 'Dejar caer el pecho; encoger los hombros; recorrido mínimo.', 'Movimiento pequeño y controlado; no busques fatiga de pecho.', 'Sumá reps o hacelo en paralelas con más protracción.', 'Protracción de rodillas apoyadas.', array['Push-up plus en paralelas', 'Push-up plus con pausa'], array['Deslizamiento en pared', 'Flexiones lastradas']),

('Y-raise en el suelo boca abajo', 'Prone floor Y-raise', 'y raise en el suelo, elevación en Y en el suelo', 'Accesorios Calistenia', 'Prehabilitación', 'Trapecio inferior', 'Accesorios Calistenia', 'Principiante', 1, 'Suelo (mancuernas livianas opcional)', 'Peso corporal', 'Aislado', 'Elevación', array['Trapecio inferior'], array['Deltoides posterior', 'Infraespinoso'], array['Romboides', 'Core'], false, 'Abierta', 'Control corporal', 3, '12-15', 45, 2, 'Fortalece el trapecio inferior y los rotadores externos, mejorando la postura y el equilibrio del hombro.', 'Boca abajo en el suelo, brazos en Y con pulgares arriba, despegá las manos del piso elevando apenas el pecho sin encoger el cuello.', 'Usar impulso; encoger los hombros; levantar demasiado el torso.', 'Movimiento chico y controlado; sumá mancuernas solo si dominás sin peso.', 'Sumá reps o mancuernas de 0,5 kg al completar 3x15 controladas.', 'Y-raise sin peso con brazos apoyados.', array['Y-raise en el suelo boca abajo', 'Y-raise a una mano'], array['Y-T-W en banco inclinado', 'Rotación externa acostado de lado']),

('Y-T-W en banco inclinado', 'Prone Y-T-W raise', 'ytw, raises en Y T W', 'Accesorios Calistenia', 'Prehabilitación', 'Trapecio inferior y medio', 'Accesorios Calistenia', 'Intermedio', 2, 'Banco inclinado y mancuernas livianas', 'Mancuernas', 'Aislado', 'Elevación', array['Trapecio inferior', 'Trapecio medio'], array['Deltoides posterior', 'Romboides'], array['Infraespinoso', 'Core'], false, 'Abierta', 'Control corporal', 3, '8-10 por letra', 60, 2, 'Secuencia completa de escápula y manguito que refuerza la salud del hombro y la postura.', 'Boca abajo, formá Y, luego T con pulgares arriba y después W con codos doblados, elevando sin encoger el cuello.', 'Impulso; hombros altos; cargas altas.', 'Sin peso al principio; series cortas y precisas.', 'Sumá 0,5-1 kg al completar 3x10 por letra.', 'Y-raise en banco inclinado.', array['Y-T-W sin peso', 'Y-T-W con pausa'], array['Y-raise en banco inclinado', 'Rotación externa a 90° de pie']),

('Rotación externa acostado de lado', 'Side-lying external rotation', 'rotación externa, manguito rotador acostado', 'Accesorios Calistenia', 'Prehabilitación', 'Manguito rotador', 'Accesorios Calistenia', 'Principiante', 1, 'Banco y mancuerna liviana', 'Mancuernas', 'Aislado', 'Rotación externa', array['Infraespinoso', 'Redondo menor'], array['Deltoides posterior'], array['Trapecio inferior', 'Core'], true, 'Abierta', 'Control corporal', 3, '12-15', 45, 2, 'Aislamiento clásico del manguito rotador para proteger el hombro en empujes y skills.', 'Acostado de lado con codo pegado al cuerpo a 90°, rotá la mancuerna hacia arriba manteniendo el codo fijo y bajá lento.', 'Mover el codo; rotar el torso; usar cargas altas.', 'Liviano y controlado; parar si hay dolor agudo.', 'Sumá 0,5 kg al completar 3x15 por lado.', 'Rotación externa sin peso.', array['Rotación externa a 45°', 'Rotación externa con pausa'], array['Rotación externa a 90° de pie', 'Y-raise en banco inclinado']),

('Rotación externa a 90° de pie', 'Standing 90/90 external rotation', 'rotación externa 90 grados', 'Accesorios Calistenia', 'Prehabilitación', 'Manguito rotador', 'Accesorios Calistenia', 'Intermedio', 2, 'Mancuerna liviana', 'Mancuernas', 'Aislado', 'Rotación externa', array['Infraespinoso', 'Redondo menor'], array['Deltoides posterior', 'Trapecio'], array['Core', 'Romboides'], true, 'Abierta', 'Control corporal', 3, '10-12 por lado', 60, 2, 'Rotación externa en posición de hombro elevado, muy específica para la preparación de handstand y planche.', 'Hombro a 90°, codo doblado a 90°, rotá el antebrazo hacia arriba sin mover el codo y bajá controlado.', 'Bajar el codo; compensar con el torso; cargar demasiado.', 'Carga muy liviana; empezá sin peso para dominar el rango.', 'Sumá 0,5 kg al completar 3x12 por lado.', 'Rotación externa acostado de lado.', array['Rotación externa 90/90 con pausa', 'Rotación externa 90/90 a dos manos'], array['Y-T-W en banco inclinado', 'Rotación externa acostado de lado']),

('Rotación interna acostado de lado', 'Side-lying internal rotation', 'rotación interna, manguito anterior', 'Accesorios Calistenia', 'Prehabilitación', 'Manguito rotador', 'Accesorios Calistenia', 'Principiante', 1, 'Banco y mancuerna liviana', 'Mancuernas', 'Aislado', 'Rotación interna', array['Subescapular'], array['Pectoral mayor', 'Dorsal ancho'], array['Core'], true, 'Abierta', 'Control corporal', 3, '12-15', 45, 2, 'Trabajo del subescapular que completa el equilibrio del manguito rotador.', 'Acostado de lado con codo a 90°, rotá la mancuerna hacia el abdomen manteniendo el codo fijo y volvé lento.', 'Mover el codo; usar impulso; cargas altas.', 'Liviano; priorizá el control del recorrido.', 'Sumá 0,5 kg al completar 3x15 por lado.', 'Rotación interna sin peso.', array['Rotación interna con pausa', 'Rotación interna a 45°'], array['Rotación externa acostado de lado', 'Flexión con protracción']),

('Deslizamiento en pared', 'Wall slide', 'wall slide, deslizamiento escapular', 'Accesorios Calistenia', 'Prehabilitación', 'Serrato anterior y escápula', 'Accesorios Calistenia', 'Principiante', 1, 'Pared', 'Peso corporal', 'Estabilidad', 'Elevación', array['Serrato anterior', 'Trapecio inferior'], array['Deltoides', 'Romboides'], array['Core', 'Manguito rotador'], false, 'Abierta', 'Control corporal', 3, '10-12', 45, 1, 'Ejercicio de control escapular que mejora la movilidad y estabilidad del hombro por encima de la cabeza.', 'De espaldas a la pared, antebrazos apoyados, deslizá los brazos hacia arriba sin despegar la espalda ni perder el contacto.', 'Arquear la lumbar; llevar los codos adelante; encoger los hombros.', 'Si falta movilidad, reducí el rango; no fuerces el hombro.', 'Sumá rango o reps al completar 3x12 sin perder contacto.', 'Deslizamiento con menos rango.', array['Wall slide con banda', 'Wall slide con pausa'], array['Flexión con protracción', 'Y-raise en banco inclinado']),

('Plancha Copenhagen', 'Copenhagen plank', 'copenhagen, plancha para aductores', 'Accesorios Calistenia', 'Prehabilitación', 'Aductores y core', 'Accesorios Calistenia', 'Intermedio', 3, 'Banco o cajón', 'Peso corporal', 'Estabilidad', 'Anti-flexión lateral', array['Aductores'], array['Oblicuos', 'Transverso abdominal'], array['Glúteo medio', 'Core'], true, 'Cerrada', 'Control corporal', 3, '15-25 s por lado', 60, 1, 'Plancha lateral con apoyo del pie interno que fortalece aductores y protege la ingle en saltos y patadas.', 'De costado con el pie de arriba apoyado en el banco, elevá la cadera y mantené el cuerpo alineado.', 'Cadera caída; rotar; apoyar la rodilla de abajo.', 'Empezá con la rodilla de abajo apoyada y avanzá a pierna completa.', 'Sumá segundos hasta 3x30 s por lado.', 'Copenhagen con rodilla apoyada.', array['Copenhagen con pierna completa', 'Copenhagen dinámico'], array['Plancha frontal lastrada', 'Abducción de cadera acostado de lado']),

('Abducción de cadera acostado de lado', 'Side-lying hip abduction', 'abducción acostado, glúteo medio', 'Accesorios Calistenia', 'Prehabilitación', 'Glúteo medio', 'Accesorios Calistenia', 'Principiante', 1, 'Suelo (opcional tobillera o mancuerna)', 'Peso corporal', 'Aislado', 'Abducción de cadera', array['Glúteo medio'], array['Tensor de la fascia lata', 'Glúteo menor'], array['Core', 'Cuadrado lumbar'], true, 'Abierta', 'Control corporal', 3, '15-20 por lado', 45, 1, 'Activa el glúteo medio, estabilizador clave de rodilla y cadera durante el apoyo a una pierna.', 'Acostado de lado con la pierna de arriba extendida, subila sin rotar la cadera y bajá controlado.', 'Rotar la cadera hacia atrás; usar impulso; subir demasiado.', 'Mantené el pie apuntando al frente; movimiento lento.', 'Sumá reps o tobillera liviana al completar 3x20.', 'Abducción de pie contra la pared.', array['Abducción con pausa', 'Abducción con pierna en extensión'], array['Plancha Copenhagen', 'Puente de glúteo a una pierna']),

('Elevación de punta de pie con disco', 'Weighted tibialis raise', 'tibial anterior, dorsiflexión con peso', 'Accesorios Calistenia', 'Prehabilitación', 'Tibial anterior', 'Accesorios Calistenia', 'Principiante', 1, 'Pared y disco', 'Mixto', 'Aislado', 'Dorsiflexión', array['Tibial anterior'], array['Extensores de los dedos'], array['Core'], false, 'Cerrada', 'Resistencia', 3, '15-20', 45, 1, 'Fortalece el tibial anterior, previniendo dolor de espinilla y mejorando el control del tobillo.', 'De espaldas a la pared con los talones cerca, subí las puntas de los pies contra un disco y bajá controlando.', 'Separar los talones de la pared; usar impulso; rango corto.', 'Carga liviana; el tibial responde bien a altas repeticiones.', 'Sumá reps o peso al completar 3x20.', 'Dorsiflexión sin peso.', array['Elevación de punta de pie a una pierna', 'Elevación de punta con pausa'], array['Gemelos en escalón', 'Deslizamiento en pared']),

('Paseo del granjero con mancuernas', 'Farmer''s walk', 'acarreo del granjero, farmer walk', 'Accesorios Calistenia', 'Cuerpo completo', 'Acarreo y core', 'Accesorios Calistenia', 'Principiante', 2, 'Mancuernas pesadas', 'Mancuernas', 'Compuesto', 'Acarreo (carry)', array['Trapecio', 'Antebrazo', 'Core'], array['Glúteos', 'Cuádriceps', 'Pantorrillas'], array['Escápula', 'Manguito rotador'], false, 'Cerrada', 'Fuerza', 3, '30-40 m', 90, 2, 'Acarreo que desarrolla agarre, trapecio y core anti-flexión mientras entrena todo el cuerpo de pie.', 'Tomá mancuernas pesadas, hombros atrás, core firme y caminá con pasos normales sin inclinarte.', 'Encorvar la espalda; encoger los hombros; pasos apurados.', 'Espacio libre; disponé las mancuernas en el suelo con espalda neutra.', 'Sumá peso o distancia al completar 3x40 m.', 'Sostén isométrico de mancuernas.', array['Paseo del granjero a una mano', 'Paseo del granjero con mancuerna sobre la cabeza'], array['Sostén isométrico de mancuernas', 'Peso muerto con barra']),

('Clean and press con barra', 'Clean and press', 'cargada y press', 'Accesorios Calistenia', 'Cuerpo completo', 'Potencia y empuje', 'Accesorios Calistenia', 'Avanzado', 3, 'Barra y discos', 'Barra', 'Compuesto', 'Potencia', array['Glúteos', 'Cuádriceps', 'Deltoides anterior'], array['Erectores espinales', 'Trapecio', 'Tríceps braquial'], array['Core', 'Pantorrillas'], false, 'Cerrada', 'Potencia', 4, '5-6', 150, 2, 'Movimiento global que entrena potencia de cadera, coordinación y empuje por encima de la cabeza.', 'Del suelo al hombro con extensión de cadera y luego press sobre la cabeza, encadenando ambos gestos.', 'Tirar con los brazos; redondear la espalda; no coordinar cadera y hombros.', 'Aprendé la cargada por separado antes de encadenar; usá seguros.', 'Subí 2,5 kg al completar 4x6 técnicos.', 'Clean and press con mancuerna a una mano.', array['Power clean y press', 'Clean and jerk'], array['Cargada de potencia con barra', 'Thruster con barra']),

('Thruster con barra', 'Barbell thruster', 'thruster, sentadilla y press', 'Accesorios Calistenia', 'Cuerpo completo', 'Potencia y empuje', 'Accesorios Calistenia', 'Intermedio', 3, 'Barra y discos', 'Barra', 'Compuesto', 'Potencia', array['Cuádriceps', 'Glúteo mayor', 'Deltoides anterior'], array['Tríceps braquial', 'Erectores espinales'], array['Core', 'Pantorrillas'], false, 'Cerrada', 'Potencia', 4, '6-8', 150, 2, 'Combinación de sentadilla frontal y press que dispara el pulso y la potencia total.', 'Barra en hombros, bajá a sentadilla frontal y al subir usá el impulso para empujar la barra sobre la cabeza.', 'Cortar la profundidad; empujar con los brazos sin piernas; perder el core.', 'Cuidá el ritmo cardíaco; empezá con barra liviana.', 'Sumá 2,5 kg al completar 4x8 con profundidad.', 'Thruster con mancuernas.', array['Thruster con mancuernas', 'Front squat + press separados'], array['Clean and press con barra', 'Sentadilla frontal con barra']),

('Cargada de potencia con barra', 'Power clean', 'power clean, cargada', 'Accesorios Calistenia', 'Cuerpo completo', 'Potencia de cadera', 'Accesorios Calistenia', 'Avanzado', 4, 'Barra y discos', 'Barra', 'Compuesto', 'Potencia', array['Glúteos', 'Isquiotibiales', 'Trapecio'], array['Cuádriceps', 'Erectores espinales'], array['Core', 'Agarre'], false, 'Cerrada', 'Potencia', 5, '3-5', 180, 3, 'Levantamiento explosivo que construye potencia de cadera, coordinación y fuerza general.', 'Del suelo, extendé la cadera explosivamente y recibí la barra en hombros con codos altos.', 'Tirar con los brazos temprano; redondear la espalda; recibir con codos bajos.', 'Técnica primero; cargas moderadas y progresión lenta.', 'Subí 2,5 kg al completar 5x3 con recepción sólida.', 'Cargada con mancuernas o desde colgado.', array['Power clean desde colgado', 'Power clean al frente'], array['Clean and press con barra', 'Peso muerto con barra']),

('Snatch con mancuerna', 'Dumbbell snatch', 'snatch, arrancada con mancuerna', 'Accesorios Calistenia', 'Cuerpo completo', 'Potencia unilateral', 'Accesorios Calistenia', 'Avanzado', 3, 'Mancuerna', 'Mancuernas', 'Compuesto', 'Potencia', array['Glúteos', 'Deltoides', 'Trapecio'], array['Cuádriceps', 'Isquiotibiales', 'Core'], array['Agarre', 'Pantorrillas'], true, 'Cerrada', 'Potencia', 4, '4-6 por lado', 150, 3, 'Movimiento explosivo unilateral que entrena potencia de cadera y estabilidad del hombro.', 'Desde el suelo, extendé la cadera y llevá la mancuerna en un solo movimiento sobre la cabeza con el brazo recto.', 'Doblar el codo temprano; redondear la espalda; perder control arriba.', 'Empezá liviano; cuidá el hombro y la muñeca.', 'Sumá 1-2 kg al completar 4x6 por lado.', 'Snatch con mancuerna desde colgado.', array['Snatch alternado', 'Snatch con barra liviana'], array['Cargada de potencia con barra', 'Clean and press con barra']),

('Burpee con lastre', 'Weighted burpee', 'burpee con peso, burpee lastrado', 'Accesorios Calistenia', 'Cuerpo completo', 'Resistencia y potencia', 'Accesorios Calistenia', 'Intermedio', 3, 'Chaleco o disco', 'Peso corporal', 'Compuesto', 'Cuerpo completo', array['Cuádriceps', 'Glúteo mayor', 'Pectoral mayor'], array['Tríceps braquial', 'Deltoides', 'Core'], array['Pantorrillas', 'Erector espinal'], false, 'Cerrada', 'Resistencia', 4, '8-12', 90, 1, 'Trabajo metabólico total con carga que combina fuerza, coordinación y capacidad aeróbica.', 'Desde de pie, bajá a flexión, hacé una flexión, saltá los pies al frente y saltá extendido; la carga suma exigencia.', 'Cadera caída en la flexión; no extender del todo el salto; perder el ritmo.', 'Dosificá el volumen; el lastre acelera la fatiga.', 'Sumá reps o peso cuando 4x12 resulten cómodas.', 'Burpee a peso corporal.', array['Burpee sobre cajón', 'Burpee con flexión lastrada'], array['Thruster con barra', 'Paseo del granjero con mancuernas']),

('Dislocaciones de hombro con barra', 'Shoulder dislocates', 'dislocaciones, pass through', 'Accesorios Calistenia', 'Movilidad', 'Movilidad de hombro', 'Accesorios Calistenia', 'Principiante', 1, 'Barra, palo o toalla', 'Peso corporal', 'Movilidad', 'Movilidad', array['Deltoides', 'Pectoral mayor'], array['Trapecio', 'Romboides'], array['Manguito rotador', 'Core'], false, 'Abierta', 'Movilidad', 3, '10-15', 30, 0, 'Movilidad global de hombro que prepara la articulación para handstand, planche y anillas.', 'Con la barra frente al cuerpo y brazos extendidos, pasala por encima de la cabeza hasta la espalda y volvé, sin doblar codos.', 'Doblar los codos; arquear la lumbar; forzar el rango.', 'Agarre ancho al principio; reducí el ancho a medida que mejora la movilidad.', 'Estrechá el agarre o sumá reps al dominar 3x15 sin dolor.', 'Dislocaciones con toalla o agarre más ancho.', array['Dislocaciones con pausa', 'Dislocaciones con banda'], array['Movilidad 90/90 de cadera', 'Rotación torácica en cuadrupedia']),

('Sentadilla profunda sostenida', 'Deep squat hold', 'sentadilla profunda, deep squat', 'Accesorios Calistenia', 'Movilidad', 'Movilidad de cadera y tobillo', 'Accesorios Calistenia', 'Principiante', 1, 'Suelo', 'Peso corporal', 'Movilidad', 'Movilidad', array['Cuádriceps', 'Glúteos', 'Aductores'], array['Pantorrillas', 'Flexores de cadera'], array['Core'], false, 'Abierta', 'Movilidad', 3, '30-60 s', 30, 0, 'Movilidad de cadera, tobillo y columna que sostiene el rango necesario para sentadillas y pistols.', 'Bajá a sentadilla profunda con talones apoyados, rodillas afuera y pecho alto; sostené respirando.', 'Levantar los talones; redondear la espalda; aguantar la respiración.', 'Usá un apoyo bajo los talones o sujetate de algo si falta movilidad.', 'Sumá tiempo o llegá a profundidad con talones apoyados.', 'Sentadilla profunda sosteniéndose de un apoyo.', array['Sentadilla profunda con pausa y balanceo', 'Sentadilla profunda con codos empujando rodillas'], array['Movilidad 90/90 de cadera', 'Estiramiento de flexores de cadera']),

('Movilidad 90/90 de cadera', '90/90 hip switch', '90/90, movilidad de cadera', 'Accesorios Calistenia', 'Movilidad', 'Movilidad de cadera', 'Accesorios Calistenia', 'Intermedio', 2, 'Suelo', 'Peso corporal', 'Movilidad', 'Movilidad', array['Glúteos', 'Aductores', 'Rotadores de cadera'], array['Cuádriceps', 'Isquiotibiales'], array['Core'], false, 'Abierta', 'Movilidad', 3, '8-10 por lado', 30, 0, 'Movilidad activa de cadera en rotación interna y externa, excelente para patadas, pistols y saltos.', 'Sentado con ambas rodillas a 90°, girás de un lado al otro pasando por encima sin usar las manos.', 'Redondear la espalda; colapsar la cadera; usar impulso.', 'Empezá apoyando las manos; mové dentro de un rango sin dolor.', 'Sumá reps y eliminá la ayuda de las manos.', '90/90 con apoyo de manos.', array['90/90 con pausa', '90/90 con levantamiento de rodilla'], array['Sentadilla profunda sostenida', 'Estiramiento de flexores de cadera']),

('Estiramiento de flexores de cadera', 'Hip flexor stretch', 'couch stretch, estiramiento de psoas', 'Accesorios Calistenia', 'Movilidad', 'Movilidad de cadera', 'Accesorios Calistenia', 'Principiante', 1, 'Suelo o banco', 'Peso corporal', 'Movilidad', 'Movilidad', array['Flexores de cadera'], array['Cuádriceps'], array['Core', 'Glúteos'], true, 'Abierta', 'Movilidad', 2, '30-45 s por lado', 30, 0, 'Estiramiento del psoas y flexores que abre la cadera y mejora la postura en handstand y L-sit.', 'En media rodilla o con el pie apoyado en un banco, meté la pelvis, elevá el torso y llevá la cadera adelante.', 'Arquear la lumbar; girar la pelvis; rebotar.', 'Movete suave; el estiramiento profundo no debe doler.', 'Sumá tiempo o separá más el pie del banco.', 'Estiramiento de rodillas con cojín.', array['Couch stretch', 'Estiramiento con rotación de tronco'], array['Movilidad 90/90 de cadera', 'Sentadilla profunda sostenida']),

('Rotación torácica en cuadrupedia', 'Quadruped thoracic rotation', 'rotación torácica, thread the needle', 'Accesorios Calistenia', 'Movilidad', 'Movilidad torácica', 'Accesorios Calistenia', 'Principiante', 1, 'Suelo', 'Peso corporal', 'Movilidad', 'Movilidad', array['Erectores espinales', 'Oblicuos'], array['Romboides', 'Dorsal ancho'], array['Core', 'Trapecio'], false, 'Abierta', 'Movilidad', 3, '8-10 por lado', 30, 0, 'Movilidad de la columna torácica que mejora la rotación necesaria para tirones y skills de anillas.', 'En cuadrupedia, una mano detrás de la cabeza y girá el codo hacia el techo abriendo el pecho, volvé y repetí.', 'Girar la cadera; forzar con el brazo; perder el control del core.', 'Mantené las rodillas quietas y el movimiento en el tórax.', 'Sumá rango o reps al completar 3x10 sin dolor.', 'Rotación torácica de rodillas apoyadas.', array['Thread the needle', 'Rotación torácica sentado'], array['Dislocaciones de hombro con barra', 'Movilidad 90/90 de cadera'])

on conflict (nombre, disciplina) do nothing;

-- ============================================================
-- VERIFICACION
-- ============================================================
do $acc_verif$
declare v_total int; v_rev int; v_dup int;
begin
  select count(*) into v_total from public.exercises where disciplina = 'Accesorios Calistenia';
  select count(*) into v_rev   from public.exercises where disciplina = 'Accesorios Calistenia' and coalesce(estado_clasificacion,'') = 'a_revisar';
  select count(*) into v_dup   from public.exercises where disciplina = 'Accesorios Calistenia' and duplicado_de is not null;
  raise notice 'ACCESORIOS OK · total=% · a_revisar=% · duplicados=%', v_total, v_rev, v_dup;
end
$acc_verif$;

-- Conteo por categoria (para copiar al chat)
select categoria, count(*) as total
from public.exercises
where disciplina = 'Accesorios Calistenia'
group by categoria
order by total desc, categoria;
